const emptyTrackLists = { lectureIds: [], coreConceptIds: [], trapIds: [], quizIds: [], answerIds: [], formulaIds: [], figureIds: [], problemsSolutions: [], comparisons: [] };

export const baseTracks = [
  { id: "learning-science", title: "Learning Science Principles", subtitle: "Spaced repetition, active recall, cognitive load reduction, and metacognitive review.", color: "blue", i18n: { zh: { title: "学习科学原则", subtitle: "间隔重复、主动回忆、认知负荷降低和元认知复习。" }, mix: { title: "Learning Science 原则", subtitle: "Spaced repetition、active recall、cognitive load reduction 和 metacognitive review。" }, en: { title: "Learning Science Principles", subtitle: "Spaced repetition, active recall, cognitive load reduction, and metacognitive review." } }, ...emptyTrackLists },
  { id: "cognitive-diagnosis", title: "Cognitive Diagnosis", subtitle: "Knowledge components, mastery estimates, mistake patterns, and confidence calibration.", color: "purple", i18n: { zh: { title: "认知诊断", subtitle: "知识组件、掌握程度估计、错误模式和信心校准。" }, mix: { title: "Cognitive Diagnosis", subtitle: "Knowledge components、mastery estimates、mistake patterns 和 confidence calibration。" }, en: { title: "Cognitive Diagnosis", subtitle: "Knowledge components, mastery estimates, mistake patterns, and confidence calibration." } }, ...emptyTrackLists },
  { id: "ai-workflow", title: "AI / RAG Workflow", subtitle: "AI-ready course ingestion, retrieval-grounded generation, quiz drafting, and verification guardrails.", color: "green", i18n: { zh: { title: "AI / RAG 工作流", subtitle: "AI-ready 课程导入、基于检索的生成、测验草拟和验证护栏。" }, mix: { title: "AI / RAG Workflow", subtitle: "AI-ready course ingestion、retrieval-grounded generation、quiz drafting 和 verification guardrails。" }, en: { title: "AI / RAG Workflow", subtitle: "AI-ready course ingestion, retrieval-grounded generation, quiz drafting, and verification guardrails." } }, ...emptyTrackLists },
  { id: "prototype-engineering", title: "Prototype Engineering", subtitle: "Modular schema, frontend workflow, local learning logs, printable exports, and deployment.", color: "gold", i18n: { zh: { title: "原型工程", subtitle: "模块化 schema、前端流程、本地学习记录、可打印导出和部署。" }, mix: { title: "Prototype Engineering", subtitle: "Modular schema、frontend workflow、local learning logs、printable exports 和 deployment。" }, en: { title: "Prototype Engineering", subtitle: "Modular schema, frontend workflow, local learning logs, printable exports, and deployment." } }, ...emptyTrackLists },
  { id: "personalized-review", title: "Personalized Review Logic", subtitle: "How review queues, weak-area signals, and priority dashboards can support adaptive learning.", color: "pink", i18n: { zh: { title: "个性化复习逻辑", subtitle: "复习队列、薄弱信号和优先级仪表盘如何支持自适应学习。" }, mix: { title: "Personalized Review Logic", subtitle: "Review queues、weak-area signals 和 priority dashboards 如何支持 adaptive learning。" }, en: { title: "Personalized Review Logic", subtitle: "How review queues, weak-area signals, and priority dashboards can support adaptive learning." } }, ...emptyTrackLists },
  { id: "research-extension", title: "Research Extension Path", subtitle: "Possible ML/DL research directions in learning analytics, knowledge tracing, and educational AI.", color: "orange", i18n: { zh: { title: "研究扩展路径", subtitle: "学习分析、知识追踪和教育 AI 中可能的 ML/DL 研究方向。" }, mix: { title: "Research Extension Path", subtitle: "Learning analytics、knowledge tracing 和 educational AI 中可能的 ML/DL research directions。" }, en: { title: "Research Extension Path", subtitle: "Possible ML/DL research directions in learning analytics, knowledge tracing, and educational AI." } }, ...emptyTrackLists }
];
