import { createContext, useContext, useMemo } from "react";
import { useLocalStorage } from "../hooks/useLocalStorage.js";

const LanguageContext = createContext(null);

export const languageModes = [
  { id: "zh", label: "中文", hint: "纯中文界面" },
  { id: "mix", label: "中英", hint: "中文主体 + English terms" },
  { id: "en", label: "EN", hint: "English interface" }
];

export const uiText = {
  zh: {
    language: "语言", studyModifiers: "学习辅助", focusMode: "聚焦模式", focusModeHint: "弱化额外界面元素，突出当前学习区块", compactCards: "紧凑卡片", compactCardsHint: "每轮复习中容纳更多回忆提示", lowMotion: "低动态", lowMotionHint: "减少动效，适合长时间复习", dayMode: "日间模式", nightMode: "夜间模式",
    aiReadySurface: "AI-ready 原型界面", aiReadySurfaceNote: "公开演示使用合成课程包、诊断快捷入口和可打印导出；系统结构保留 LLM/RAG 内容导入扩展空间。", adaptiveReviewShell: "自适应复习框架", shellHeadline: "基于学习科学的复习系统，可扩展 AI 功能。",
    dueNow: "今日到期", streak: "连续天数", modules: "模块", tracks: "路径", coreLoop: "核心流程", practice: "练习", system: "系统", overview: "总览", overviewHint: "查看整体复习系统结构", projectBrief: "项目说明", projectBriefHint: "说明研究定位与原型设计", priority: "优先级", priorityHint: "决定下一步复习重点", spacedReview: "间隔复习", spacedReviewHint: "清理到期复习队列", mistakeBook: "错题本", mistakeBookHint: "快速回放薄弱信号", reviewHub: "复习中心", reviewHubHint: "压缩概念、误区和公式", quiz: "测验", quizHint: "进行主动回忆检查", traps: "误区", trapsHint: "保护容易失分的地方", formulas: "公式", formulasHint: "高对比度数学锚点", figures: "图表", figuresHint: "视觉识别训练", last30: "最后30分钟", last30Hint: "极压缩临考回顾", search: "搜索", searchHint: "直接跳转到模块和项目", printPack: "打印包", printPackHint: "导出纸质友好的复习表",
    memoryUnit: "记忆单元", exam: "考试", links: "关联", coreIdea: "核心理解", definition: "定义", whyItMatters: "为什么重要", memoryAnchor: "记忆锚点", visualMemoryBridge: "图文公式联动", figure: "图", formula: "公式", trap: "误区", trapContrast: "易错对照", examExpression: "考试表达", shortAnswer: "简答表达", examSignals: "考试信号", likelyQuestions: "可能问题", relatedQuiz: "相关题目", longAnswerBuilder: "长答案构建器", relatedConcepts: "相关概念", noLinkedConcepts: "暂无关联概念。", tags: "标签",
    longAnswer: "长答案模板", fullAnswer: "完整答案", commonMistakes: "常见错误", collapse: "收起", buildFullAnswer: "构建完整答案", memoryUnitFallback: "记忆单元", printExport: "打印 / 导出", printSavePdf: "打印 / 保存 PDF", downloadMarkdown: "下载 Markdown", printHub: "打印中心", thisRoom: "当前模块", reviewHubShort: "复习中心",
    questionTypeQuiz: "题目", true: "正确", false: "错误", yourAnswer: "你的答案", typeShortAnswer: "输入简短答案，例如 12×12", check: "检查", reset: "重置", correct: "正确。", notYet: "还不对。", answer: "答案", again: "重来", hard: "困难", good: "掌握", easy: "简单", saved: "已保存", save: "保存",
    moduleNotFound: "未找到模块", noModuleExists: "没有找到对应模块：", courseMap: "课程地图", visualMemoryMap: "视觉记忆图", structuredOverview: "二维/结构化总览", conceptMemoryUnits: "概念记忆单元", conceptMemoryUnitsEyebrow: "理解 + 图 + 公式 + trap", conceptMemoryUnitsSubtitle: "每张卡片将解释、视觉线索、公式、误区和测验绑定成一个记忆单元。", miniQuiz: "小测验", activeRecall: "主动回忆", miniQuizSubtitle: "先尝试再揭示答案。卡片会即时反馈并解释。", commonTraps: "常见误区", doNotFall: "不要掉进这些坑", commonTrapsSubtitle: "通过错误 → 正确的对照减少考试时的混淆。", figureRecognition: "图表识别", visualRecall: "视觉回忆", figureRecognitionSubtitle: "先识别架构、任务或流程，再阅读关键视觉线索。", noFiguresModule: "本模块暂无图表。", formulaCards: "公式卡片", mathAnchors: "数学锚点", formulaCardsSubtitle: "让公式与概念、图表和误区相连，而不是孤立背 LaTeX。", noFormulasModule: "本模块暂无公式。", longFormReviewPrep: "长答案复习准备", longAnswerSubtitle: "先用框架作答，再与完整答案对照。"
  },
  mix: {
    language: "Language", studyModifiers: "学习 modifiers", focusMode: "Focus mode", focusModeHint: "弱化 extra chrome，突出 active study block", compactCards: "Compact cards", compactCardsHint: "每次 study pass 容纳更多 recall prompts", lowMotion: "Low motion", lowMotionHint: "保持界面 calm，适合长时间 evening sessions", dayMode: "Day mode", nightMode: "Night mode",
    aiReadySurface: "AI-ready surface", aiReadySurfaceNote: "Synthetic course packs、diagnostic shortcuts 和 printable exports 让 public demo 安全，同时 architecture 保留 LLM/RAG ingestion 扩展空间。", adaptiveReviewShell: "Adaptive review shell", shellHeadline: "Learning-science informed review，ready for AI extension。",
    dueNow: "Due now", streak: "Streak", modules: "Modules", tracks: "Tracks", coreLoop: "Core loop", practice: "Practice", system: "System", overview: "Overview", overviewHint: "Map the whole revision system", projectBrief: "Project brief", projectBriefHint: "Explain research and prototype framing", priority: "Priority", priorityHint: "Decide where attention goes next", spacedReview: "Spaced review", spacedReviewHint: "Clear due-item queue", mistakeBook: "Mistake book", mistakeBookHint: "Replay weak signals fast", reviewHub: "Review hub", reviewHubHint: "Condense concepts、traps 和 formulas", quiz: "Quiz", quizHint: "Run active-recall checks", traps: "Traps", trapsHint: "Protect easy marks", formulas: "Formulas", formulasHint: "High-contrast math anchors", figures: "Figures", figuresHint: "Visual recognition drills", last30: "Last 30", last30Hint: "Ultra-compressed final pass", search: "Search", searchHint: "Jump straight to modules and items", printPack: "Print pack", printPackHint: "Export paper-friendly review sheets",
    memoryUnit: "Memory Unit", exam: "Exam", links: "Links", coreIdea: "核心理解 / Core idea", definition: "Definition", whyItMatters: "Why it matters", memoryAnchor: "Memory anchor", visualMemoryBridge: "图文公式联动 / Visual memory bridge", figure: "图 / Figure", formula: "公式 / Formula", trap: "误区 / Trap", trapContrast: "易错对照 / Trap contrast", examExpression: "考试表达 / Exam expression", shortAnswer: "Short answer", examSignals: "Exam signals", likelyQuestions: "Likely questions", relatedQuiz: "Related quiz / 相关题目", longAnswerBuilder: "Long answer builder / 长答案模板", relatedConcepts: "Related concepts / 相关知识", noLinkedConcepts: "No linked concepts yet.", tags: "Tags",
    longAnswer: "Long answer / 长答案模板", fullAnswer: "Full answer / 完整答案", commonMistakes: "Common mistakes", collapse: "Collapse", buildFullAnswer: "Build full answer", memoryUnitFallback: "memory unit", printExport: "Print / Export", printSavePdf: "Print / Save PDF", downloadMarkdown: "Download Markdown", printHub: "Print Hub", thisRoom: "This room", reviewHubShort: "Review Hub",
    questionTypeQuiz: "quiz", true: "True", false: "False", yourAnswer: "Your answer", typeShortAnswer: "Type a short answer, e.g. 12×12", check: "Check", reset: "Reset", correct: "Correct.", notYet: "Not yet.", answer: "Answer", again: "Again", hard: "Hard", good: "Good", easy: "Easy", saved: "Saved", save: "Save",
    moduleNotFound: "Module not found", noModuleExists: "No module exists for", courseMap: "Course Map", visualMemoryMap: "Visual memory map", structuredOverview: "2D/structured overview", conceptMemoryUnits: "Concept memory units", conceptMemoryUnitsEyebrow: "理解 + 图 + 公式 + trap", conceptMemoryUnitsSubtitle: "Each card binds explanation、visual cue、formula、trap 和 quiz into one memory unit。", miniQuiz: "Mini quiz", activeRecall: "Active recall", miniQuizSubtitle: "Try before revealing. The card gives immediate feedback and explanation.", commonTraps: "Common traps", doNotFall: "Do not fall for these", commonTrapsSubtitle: "Use wrong → correct contrast to reduce exam-time confusion.", figureRecognition: "Figure recognition", visualRecall: "Visual recall", figureRecognitionSubtitle: "Identify the architecture、task 或 pipeline before reading key visual cue。", noFiguresModule: "No figures in this module.", formulaCards: "Formula cards", mathAnchors: "Math anchors", formulaCardsSubtitle: "Keep formulas linked with concepts、figures 和 traps rather than isolated LaTeX。", noFormulasModule: "No formulas in this module.", longFormReviewPrep: "Long-form review prep", longAnswerSubtitle: "Use skeleton first, then compare with the full answer."
  },
  en: {
    language: "Language", studyModifiers: "Study modifiers", focusMode: "Focus mode", focusModeHint: "Dim extra chrome and pull the active study block forward", compactCards: "Compact cards", compactCardsHint: "Fit more recall prompts into each study pass", lowMotion: "Low motion", lowMotionHint: "Keep the interface calm for long evening sessions", dayMode: "Day mode", nightMode: "Night mode",
    aiReadySurface: "AI-ready surface", aiReadySurfaceNote: "Synthetic course packs, diagnostic shortcuts, and printable exports keep the public demo safe while the architecture stays ready for LLM/RAG ingestion.", adaptiveReviewShell: "Adaptive review shell", shellHeadline: "Learning-science informed review, ready for AI extension.",
    dueNow: "Due now", streak: "Streak", modules: "Modules", tracks: "Tracks", coreLoop: "Core loop", practice: "Practice", system: "System", overview: "Overview", overviewHint: "Map the whole revision system", projectBrief: "Project brief", projectBriefHint: "Explain the research and prototype framing", priority: "Priority", priorityHint: "Decide where attention goes next", spacedReview: "Spaced review", spacedReviewHint: "Clear the due-item queue", mistakeBook: "Mistake book", mistakeBookHint: "Replay weak signals fast", reviewHub: "Review hub", reviewHubHint: "Condense concepts, traps, and formulas", quiz: "Quiz", quizHint: "Run active-recall checks", traps: "Traps", trapsHint: "Protect easy marks", formulas: "Formulas", formulasHint: "High-contrast math anchors", figures: "Figures", figuresHint: "Visual recognition drills", last30: "Last 30", last30Hint: "Ultra-compressed final pass", search: "Search", searchHint: "Jump straight to modules and items", printPack: "Print pack", printPackHint: "Export paper-friendly review sheets",
    memoryUnit: "Memory Unit", exam: "Exam", links: "Links", coreIdea: "Core idea", definition: "Definition", whyItMatters: "Why it matters", memoryAnchor: "Memory anchor", visualMemoryBridge: "Visual memory bridge", figure: "Figure", formula: "Formula", trap: "Trap", trapContrast: "Trap contrast", examExpression: "Exam expression", shortAnswer: "Short answer", examSignals: "Exam signals", likelyQuestions: "Likely questions", relatedQuiz: "Related quiz", longAnswerBuilder: "Long answer builder", relatedConcepts: "Related concepts", noLinkedConcepts: "No linked concepts yet.", tags: "Tags",
    longAnswer: "Long answer", fullAnswer: "Full answer", commonMistakes: "Common mistakes", collapse: "Collapse", buildFullAnswer: "Build full answer", memoryUnitFallback: "memory unit", printExport: "Print / Export", printSavePdf: "Print / Save PDF", downloadMarkdown: "Download Markdown", printHub: "Print Hub", thisRoom: "This room", reviewHubShort: "Review Hub",
    questionTypeQuiz: "quiz", true: "True", false: "False", yourAnswer: "Your answer", typeShortAnswer: "Type a short answer, e.g. 12×12", check: "Check", reset: "Reset", correct: "Correct.", notYet: "Not yet.", answer: "Answer", again: "Again", hard: "Hard", good: "Good", easy: "Easy", saved: "Saved", save: "Save",
    moduleNotFound: "Module not found", noModuleExists: "No module exists for", courseMap: "Course Map", visualMemoryMap: "Visual memory map", structuredOverview: "2D/structured overview", conceptMemoryUnits: "Concept memory units", conceptMemoryUnitsEyebrow: "Understanding + figure + formula + trap", conceptMemoryUnitsSubtitle: "Each card tries to bind explanation, visual cue, formula, trap and quiz into one memory unit.", miniQuiz: "Mini quiz", activeRecall: "Active recall", miniQuizSubtitle: "Try before revealing. The card gives immediate feedback and explanation.", commonTraps: "Common traps", doNotFall: "Do not fall for these", commonTrapsSubtitle: "Use wrong → correct contrast to reduce exam-time confusion.", figureRecognition: "Figure recognition", visualRecall: "Visual recall", figureRecognitionSubtitle: "Identify the architecture, task, or pipeline before reading the key visual cue.", noFiguresModule: "No figures in this module.", formulaCards: "Formula cards", mathAnchors: "Math anchors", formulaCardsSubtitle: "Keep formulas linked with concepts, figures and traps rather than memorizing them as isolated LaTeX.", noFormulasModule: "No formulas in this module.", longFormReviewPrep: "Long-form review prep", longAnswerSubtitle: "Use skeleton first, then compare with the full answer."
  }
};



Object.assign(uiText.zh, {
  theme: "主题", themeMode: "主题模式", nightTheme: "夜间", nightThemeHint: "低眩光深色复习界面", dayTheme: "日间", dayThemeHint: "明亮、接近纸面的复习界面",
  zhModeLabel: "中文", zhModeHint: "纯中文界面", mixModeLabel: "中英", mixModeHint: "中文主体 + 英文术语", enModeLabel: "英文", enModeHint: "纯英文界面",
  concepts: "概念", quizzes: "测验", visualCue: "视觉线索", visualCueLabel: "视觉线索", bookmarkQuiz: "收藏测验", relatedMemoryAnchors: "相关记忆锚点", memoryModeControls: "学习模式控制", languageDisplayMode: "语言显示模式", weakAreaRadarChart: "薄弱区域雷达图", showMapLinks: "显示图谱关联", contentTabs: "内容标签页", closeDrawer: "关闭抽屉",
  quizPracticeTitle: "主动回忆模式", quizPracticeIntro: "先选择或输入答案，再揭示反馈。", filterQuiz: "筛选测验", questionsShown: "个题目", searchQuestionsPlaceholder: "搜索题目，例如间隔重复、检索增强、结构模式", allCategories: "全部类别",
  readRecallStop: "阅读、回忆、然后停止", lastThirtyCompressedIntro: "高压缩复习页：高价值句子、误区、公式、图表和长答案框架。", coreMemoryLines: "核心记忆句", noFreeMarkTraps: "容易失分的误区", doNotConfuseThese: "不要混淆这些", oneGlanceRecall: "一眼回忆", figureRecognitionAnchors: "图表识别锚点", visualQuestions: "视觉问题", longAnswerSkeletons: "长答案框架",
  progressSummary: "进度摘要", localMemory: "本地记录", wrongAnswersWeakSaved: "错误答案、薄弱项目、收藏卡片", localOnlyProgress: "本页面仅使用本地浏览器记录，可随时重置。", quizItemsWithMistakes: "有错误的测验项", againHardReviewCards: "重来 / 困难复习卡", savedCardsLabel: "收藏卡片", resetLocalProgress: "重置本地进度", wrongQuizAnswers: "错误测验答案", fixTheseFirst: "优先修正", weakRecall: "薄弱回忆", manualBookmarks: "手动收藏", correctTimes: "正确 ×", savedReferences: "收藏参考",
  exportPrintMode: "导出 / 打印模式", printableRevisionPack: "可打印复习包", printHubMainIntro: "生成浏览器可打印的复习表，或下载 Markdown 文件用于离线复习。", quizItems: "测验项", printPages: "打印页面", browserPrintPdf: "浏览器打印 / 保存 PDF", staticMarkdownExports: "静态 Markdown 导出", offlineCopy: "离线副本", printable: "可打印", printableCheatSheet: "可打印速查表", printableCheatSheetDesc: "高价值复习句、概念、误区、公式和长答案提示的压缩整合。", longAnswerSheet: "长答案表", longAnswerSheetDesc: "按模块整理的长答案模板。", trapSheet: "误区表", trapSheetDesc: "错误说法 → 修正 → 原因，用于快速保护分数。", formulaSheet: "公式表", formulaSheetDesc: "所有公式锚点、变量、示例和考试提示。", offlineQuizSheet: "离线测验表", offlineQuizSheetDesc: "前半部分题目，后半部分答案，用于纸面主动回忆。",
  priorityDashboardTitle: "优先级仪表盘", priorityDashboardHeadline: "引导下一段学习，而不只是下一页。", priorityDashboardIntro: "这个界面用于快速回答：为了获得最高价值的学习信号，下一步应回忆什么？", openDueQueue: "打开到期队列", inspectWeakItems: "检查薄弱项目", learningStatus: "学习状态", todaysStudyPulse: "今日学习脉搏", pulseIntro: "三个视角：测验正确率、复习稳定性和最近两周学习节奏。", quizAccuracy: "测验正确率", quizAccuracyNote: "全部测验记录中的正确答案占比。", reviewStability: "复习稳定性", reviewStabilityNote: "以掌握或简单结束的复习占比。", fourteenDayRhythm: "14天节奏", fourteenDayRhythmNote: "最近14天中出现学习行为的频率。", dueQueueNote: "张卡片已经到期。需要系统安排回忆顺序时，从这里开始。", againHardItems: "重来 / 困难项目", quizSlips: "测验失误", startRecallLoop: "开始回忆循环", thirtyMinutePass: "30分钟速过", consistency: "一致性", studyHeatmapTitle: "学习热力图", heatmapIntro: "每个方块代表一天的测验与复习行为，颜色越明显表示学习密度越高。", weakAreaReflection: "薄弱区域反思", pressureByTrack: "按路径显示压力", radarIntro: "雷达图强调错误、到期复习和概念密度在当前课程模型中的集中位置。", moduleSequence: "模块顺序", modulePressureMap: "模块压力图", modulePressureSubtitle: "当你希望按模块推进而不是按路径推进时，使用这条通道。", priorityModules: "优先模块", modulePressure: "模块压力", moduleLaneIntro: "当你希望先集中通过一个模块，再跨路径跳转时，使用这条模块通道。", moduleCode: "模块代码", openModuleRoom: "打开模块房间", highYieldConcepts: "个高价值概念", conceptPriorityLayer: "概念优先层", conceptPrioritySubtitle: "按路径筛选，以缩小下一轮刻意复习的概念范围。", highPriorityQuizCards: "高优先级测验卡", highPriorityTraps: "高优先级误区", highPriorityLongAnswers: "高优先级长答案", fastScoreProtection: "快速保护分数",
  projectBriefTitle: "项目说明", staticToAdaptiveTitle: "从静态复习资料到自适应考试准备。", projectBriefIntro: "Modular Exam Revision Hub 是一个自发构建、可接入人工智能的网页原型，用于探索学习科学原则和机器学习友好的数据结构如何支持更结构化、互动化、可诊断的考试复习。", openPrototype: "打开原型", viewPrintablePack: "查看打印包", positioning: "定位", prototype: "原型", conceptToDemoWorkflow: "从概念到演示的工作流", data: "数据", synthetic: "合成", noRealCourseMaterials: "不含真实课程材料", architecture: "架构", modular: "模块化", replaceableCoursePacks: "课程包可替换", extension: "扩展", aiReady: "可接入人工智能", ragIngestionPath: "检索增强导入路径", motivation: "动机", whyPrototypeExists: "为什么做这个原型", whyPrototypeExistsSubtitle: "许多学生从分散的幻灯片、笔记、截图和错题中复习。通用人工智能学习工具可以生成内容，但常常没有把完整考试流程组织成清晰系统。", learningScienceLayer: "学习科学层", learningScienceLayerText: "复习流程参考间隔重复、主动回忆、认知负荷降低和基于错误的元认知复习，目标是把用户从被动阅读转向结构化回忆。", mlReadyLayer: "机器学习就绪层", mlReadyLayerText: "内容与交互模型为未来的测验记录、信心信号、复习间隔和错误模式预留结构，可支持知识追踪和认知诊断。", currentMvp: "当前最小可行原型", mvpTitle: "粗原型已经展示了什么", mvpSubtitle: "当前版本刻意保持轻量，使用结构化合成内容展示产品逻辑、界面结构和迭代路径。", aiExtensionRoadmap: "人工智能扩展路线", genuinelyInteractiveTitle: "如何变成真正互动的系统", genuinelyInteractiveSubtitle: "更稳妥的下一步不是声称训练新模型，而是连接大模型/检索增强的课程内容导入与个性化复习生成。",
  mvpItem1: "课程/模块选择与可替换的合成内容包", mvpItem2: "概念卡、主动回忆测验、常见误区卡、公式练习和图表识别", mvpItem3: "错题本、间隔复习队列、优先级仪表盘和可打印复习表", mvpItem4: "基于 LocalStorage 的原型学习记录，无需后端即可快速迭代", roadmapItem1: "基于大模型/检索增强的用户课程材料导入", roadmapItem2: "自动生成概念对象、测验、误区、公式、图表和长答案提示", roadmapItem3: "基于测验记录和错误模式的知识追踪与认知诊断层", roadmapItem4: "后端/API 集成，用于持久用户记录和多课程管理",
  printableCheatSheetTitle: "可打印速查表", printableCheatSheetSubtitle: "压缩考试综合页。使用浏览器打印并选择保存为 PDF。", syntheticDemoLearningScience: "合成演示 - 学习科学 / 可接入人工智能复习原型", generatedFromModules: "由模块化内容包生成：", courseEvolution: "课程演化", lastThirtyLines: "最后30分钟句子", coreConcepts: "核心概念", wrong: "错误", correctLabel: "正确", why: "原因", highProbabilityLongAnswers: "高概率长答案", groupedByModule: "按模块分组", formulasGroupedByModule: "个公式，按模块分组。", answersGroupedByModule: "个答案模板，按模块分组。", quizGroupedByModule: "个测验项，按模块分组。", trapsGroupedByModule: "个误区，按模块分组。", keywords: "关键词", answerKey: "答案", seeExplanation: "见解释", questionPagesFirst: "先打印题目页，再打印答案页。", wrongCorrectionWhy: "错误说法 → 修正 → 原因。",
  pageNotFoundTitle: "页面未找到", pageNotFoundBody: "这个复习房间不存在。请回到总览。", backToOverview: "返回总览"
});

Object.assign(uiText.mix, {
  theme: "Theme", themeMode: "Theme mode", nightTheme: "Night", nightThemeHint: "低眩光 dark review UI", dayTheme: "Day", dayThemeHint: "明亮 paper-like review UI",
  zhModeLabel: "中文", zhModeHint: "Chinese UI", mixModeLabel: "中英", mixModeHint: "中文主体 + English terms", enModeLabel: "EN", enModeHint: "English UI",
  concepts: "Concepts", quizzes: "Quizzes", visualCue: "Visual cue", visualCueLabel: "Visual cue", bookmarkQuiz: "Bookmark quiz", relatedMemoryAnchors: "Related memory anchors", memoryModeControls: "Memory mode controls", languageDisplayMode: "Language display mode", weakAreaRadarChart: "Weak-area radar chart", showMapLinks: "Show map links", contentTabs: "Content tabs", closeDrawer: "Close drawer",
  quizPracticeTitle: "Active recall mode", quizPracticeIntro: "先 commit to an option，再 reveal feedback。", filterQuiz: "Filter quiz", questionsShown: "questions shown", searchQuestionsPlaceholder: "Search questions, e.g. spaced repetition, RAG, schema", allCategories: "All categories",
  readRecallStop: "Read, recall, then stop", lastThirtyCompressedIntro: "Compressed final pass：high-yield lines、traps、formulas、figures 和 long-answer skeletons。", coreMemoryLines: "Core memory lines", noFreeMarkTraps: "No-free-mark traps", doNotConfuseThese: "Do not confuse these", oneGlanceRecall: "One-glance recall", figureRecognitionAnchors: "Figure recognition anchors", visualQuestions: "Visual questions", longAnswerSkeletons: "Long-answer skeletons",
  progressSummary: "Progress summary", localMemory: "Local memory", wrongAnswersWeakSaved: "Wrong answers、weak items、saved cards", localOnlyProgress: "本页面 local-only：progress 存在 browser localStorage，可随时 reset。", quizItemsWithMistakes: "Quiz items with mistakes", againHardReviewCards: "Again / Hard review cards", savedCardsLabel: "Saved cards", resetLocalProgress: "Reset local progress", wrongQuizAnswers: "Wrong quiz answers", fixTheseFirst: "Fix these first", weakRecall: "Weak recall", manualBookmarks: "Manual bookmarks", correctTimes: "correct ×", savedReferences: "Saved references",
  exportPrintMode: "Export / Print mode", printableRevisionPack: "Printable revision pack", printHubMainIntro: "Generate browser-printable sheets 或 download static Markdown files for offline review。", quizItems: "Quiz items", printPages: "Print pages", browserPrintPdf: "Browser print / Save as PDF", staticMarkdownExports: "Static Markdown exports", offlineCopy: "Offline copy", printable: "Printable", printableCheatSheet: "Printable cheat sheet", printableCheatSheetDesc: "高价值 review lines、concepts、traps、formulas 和 long-answer prompts 的 compact synthesis。", longAnswerSheet: "Long-answer sheet", longAnswerSheetDesc: "Long-answer templates grouped by module。", trapSheet: "Trap sheet", trapSheetDesc: "Wrong statement → correction → why，用于 quick mark protection。", formulaSheet: "Formula sheet", formulaSheetDesc: "All formula anchors with variables, examples, and exam notes。", offlineQuizSheet: "Offline quiz sheet", offlineQuizSheetDesc: "Questions first, answer key later，用于 paper-based active recall。",
  priorityDashboardTitle: "Priority dashboard", priorityDashboardHeadline: "Guide the next study block, not just the next page.", priorityDashboardIntro: "这个 surface 快速回答：为了最高价值的 learning signal，下一步该 recall 什么？", openDueQueue: "Open due queue", inspectWeakItems: "Inspect weak items", learningStatus: "Learning status", todaysStudyPulse: "Today’s study pulse", pulseIntro: "Three lenses：quiz accuracy、review stability、14-day rhythm。", quizAccuracy: "Quiz accuracy", quizAccuracyNote: "Correct answers across all recorded quiz attempts。", reviewStability: "Review stability", reviewStabilityNote: "Reviews ending in Good or Easy 的占比。", fourteenDayRhythm: "14-day rhythm", fourteenDayRhythmNote: "最近14天 show up 的频率。", dueQueueNote: "Cards are due now. 需要系统安排 recall order 时从这里开始。", againHardItems: "Again / Hard items", quizSlips: "Quiz slips", startRecallLoop: "Start recall loop", thirtyMinutePass: "30-minute pass", consistency: "Consistency", studyHeatmapTitle: "Study heatmap", heatmapIntro: "每个 square 代表一天的 quiz attempts + review actions；tile 越亮 session 越密。", weakAreaReflection: "Weak-area reflection", pressureByTrack: "Pressure by track", radarIntro: "Radar 强调 mistakes、due reviews 和 concept density 在当前 course model 中的集中位置。", moduleSequence: "Module sequence", modulePressureMap: "Module pressure map", modulePressureSubtitle: "想 module-by-module 推进而不是 by track 时使用这条 lane。", priorityModules: "Priority modules", modulePressure: "Module pressure", moduleLaneIntro: "Use this module lane for a focused pass before jumping across tracks。", moduleCode: "Module code", highYieldConcepts: "high-yield concepts", conceptPriorityLayer: "Concept priority layer", conceptPrioritySubtitle: "Filter by track，缩小下一轮 deliberate review 的范围。", highPriorityQuizCards: "High-priority quiz cards", highPriorityTraps: "High-priority traps", highPriorityLongAnswers: "High-priority long answers", fastScoreProtection: "Fast score protection",
  projectBriefTitle: "Project brief", staticToAdaptiveTitle: "From static revision notes to adaptive exam preparation.", projectBriefIntro: "Modular Exam Revision Hub 是 self-initiated、AI-ready web prototype，用于探索 learning science 和 ML-ready data structures 如何支持 structured、interactive、diagnosable exam preparation。", openPrototype: "Open prototype", viewPrintablePack: "View printable pack", positioning: "Positioning", prototype: "Prototype", conceptToDemoWorkflow: "Concept-to-demo workflow", data: "Data", synthetic: "Synthetic", noRealCourseMaterials: "No real course materials", architecture: "Architecture", modular: "Modular", replaceableCoursePacks: "Replaceable course packs", extension: "Extension", aiReady: "AI-ready", ragIngestionPath: "RAG ingestion path", motivation: "Motivation", whyPrototypeExists: "Why this prototype exists", whyPrototypeExistsSubtitle: "学生常从 scattered slides、notes、screenshots 和 past mistakes 中复习。Generic AI study tools 可以生成内容，但未必组织 whole exam workflow。", learningScienceLayer: "Learning-science layer", learningScienceLayerText: "Review flow 参考 spaced repetition、active recall、cognitive-load reduction 和 mistake-based metacognitive review。", mlReadyLayer: "ML-ready layer", mlReadyLayerText: "Content and interaction model 为 future quiz attempts、confidence signals、review intervals 和 mistake patterns 预留结构，可支持 knowledge tracing 和 cognitive diagnosis。", currentMvp: "Current MVP", mvpTitle: "What the rough prototype already demonstrates", mvpSubtitle: "当前版本 intentionally lightweight，用 structured synthetic content 展示 product logic、interface structure 和 iteration path。", aiExtensionRoadmap: "AI extension roadmap", genuinelyInteractiveTitle: "How this can become genuinely interactive", genuinelyInteractiveSubtitle: "下一步不是 claim training a new model，而是 connect with LLM/RAG-based course-content ingestion 和 personalised review generation。",
  mvpItem1: "Course/module selection with replaceable synthetic content packs", mvpItem2: "Concept cards, active-recall quizzes, common-trap cards, formula practice, and figure recognition", mvpItem3: "Mistake book, spaced-review queue, priority dashboard, and printable review sheets", mvpItem4: "LocalStorage-based prototype learning records for quick iteration without backend setup", roadmapItem1: "LLM/RAG-based course-content ingestion from user-provided materials", roadmapItem2: "Automatic generation of concept objects, quizzes, traps, formulas, figures, and long-answer prompts", roadmapItem3: "Knowledge tracing and cognitive-diagnosis layer based on quiz attempts and mistake patterns", roadmapItem4: "Backend/API integration for persistent user records and multi-course management",
  printableCheatSheetTitle: "Printable cheat sheet", printableCheatSheetSubtitle: "Compact exam synthesis. Use browser Print and Save as PDF.", syntheticDemoLearningScience: "Synthetic demo - Learning science / AI-ready revision prototype", generatedFromModules: "Generated from modular content packs", courseEvolution: "Course evolution", lastThirtyLines: "Last 30-minute lines", coreConcepts: "Core concepts", wrong: "Wrong", correctLabel: "Correct", why: "Why", highProbabilityLongAnswers: "High-probability long answers", groupedByModule: "grouped by module", formulasGroupedByModule: "formulas grouped by module.", answersGroupedByModule: "answer templates grouped by module.", quizGroupedByModule: "quiz items grouped by module.", trapsGroupedByModule: "traps grouped by module.", keywords: "Keywords", answerKey: "Answer key", seeExplanation: "See explanation", questionPagesFirst: "Print question pages first, then answer key.", wrongCorrectionWhy: "Wrong statement → correction → why.", pageNotFoundTitle: "Page not found", pageNotFoundBody: "This revision room does not exist. Return to overview."
});

Object.assign(uiText.en, {
  theme: "Theme", themeMode: "Theme mode", nightTheme: "Night", nightThemeHint: "Low-glare dark review interface", dayTheme: "Day", dayThemeHint: "Bright paper-like review interface",
  zhModeLabel: "Chinese", zhModeHint: "Chinese interface", mixModeLabel: "Mixed", mixModeHint: "Chinese body with English terms", enModeLabel: "English", enModeHint: "English interface",
  concepts: "Concepts", quizzes: "Quizzes", visualCue: "Visual cue", visualCueLabel: "Visual cue", bookmarkQuiz: "Bookmark quiz", relatedMemoryAnchors: "Related memory anchors", memoryModeControls: "Memory mode controls", languageDisplayMode: "Language display mode", weakAreaRadarChart: "Weak-area radar chart", showMapLinks: "Show map links", contentTabs: "Content tabs", closeDrawer: "Close drawer",
  quizPracticeTitle: "Active recall mode", quizPracticeIntro: "Reveal answers only after you commit to an option.", filterQuiz: "Filter quiz", questionsShown: "questions shown", searchQuestionsPlaceholder: "Search questions, e.g. spaced repetition, RAG, schema", allCategories: "All categories",
  readRecallStop: "Read, recall, then stop", lastThirtyCompressedIntro: "A compressed review page: high-yield sentences, traps, formulas, diagrams, and long-answer skeletons.", coreMemoryLines: "Core memory lines", noFreeMarkTraps: "No-free-mark traps", doNotConfuseThese: "Do not confuse these", oneGlanceRecall: "One-glance recall", figureRecognitionAnchors: "Figure recognition anchors", visualQuestions: "Visual questions", longAnswerSkeletons: "Long-answer skeletons",
  progressSummary: "Progress summary", localMemory: "Local memory", wrongAnswersWeakSaved: "Wrong answers, weak items, saved cards", localOnlyProgress: "This page is local-only. Your progress is stored in browser localStorage and can be reset anytime.", quizItemsWithMistakes: "Quiz items with mistakes", againHardReviewCards: "Again / Hard review cards", savedCardsLabel: "Saved cards", resetLocalProgress: "Reset local progress", wrongQuizAnswers: "Wrong quiz answers", fixTheseFirst: "Fix these first", weakRecall: "Weak recall", manualBookmarks: "Manual bookmarks", correctTimes: "correct ×", savedReferences: "Saved references",
  exportPrintMode: "Export / Print mode", printableRevisionPack: "Printable revision pack", printHubMainIntro: "Generate browser-printable sheets or download static Markdown files for offline review.", quizItems: "Quiz items", printPages: "Print pages", browserPrintPdf: "Browser print / Save as PDF", staticMarkdownExports: "Static Markdown exports", offlineCopy: "Offline copy", printable: "Printable", printableCheatSheet: "Printable cheat sheet", printableCheatSheetDesc: "One compact synthesis of high-yield review lines, concepts, traps, formulas, and long-answer prompts.", longAnswerSheet: "Long-answer sheet", longAnswerSheetDesc: "Long-answer templates grouped by module.", trapSheet: "Trap sheet", trapSheetDesc: "Wrong statement → correction → why. Designed for quick mark protection.", formulaSheet: "Formula sheet", formulaSheetDesc: "All formula anchors with variables, examples, and exam notes.", offlineQuizSheet: "Offline quiz sheet", offlineQuizSheetDesc: "Questions first, answer key later, for paper-based active recall.",
  priorityDashboardTitle: "Priority dashboard", priorityDashboardHeadline: "Guide the next study block, not just the next page.", priorityDashboardIntro: "This surface answers one question quickly: what should you recall next if you want the highest-value learning signal with the lowest wasted effort?", openDueQueue: "Open due queue", inspectWeakItems: "Inspect weak items", learningStatus: "Learning status", todaysStudyPulse: "Today’s study pulse", pulseIntro: "Three lenses: quiz accuracy, review stability, and study consistency across the last two weeks.", quizAccuracy: "Quiz accuracy", quizAccuracyNote: "Correct answers across all recorded quiz attempts.", reviewStability: "Review stability", reviewStabilityNote: "Share of reviews that ended in Good or Easy.", fourteenDayRhythm: "14-day rhythm", fourteenDayRhythmNote: "How often you showed up across the last 14 days.", dueQueueNote: "Cards are due now. Start here when you want the system to drive the order of recall.", againHardItems: "Again / Hard items", quizSlips: "Quiz slips", startRecallLoop: "Start recall loop", thirtyMinutePass: "30-minute pass", consistency: "Consistency", studyHeatmapTitle: "Study heatmap", heatmapIntro: "Each square represents one day of quiz attempts plus review actions. The brighter the tile, the denser the session.", weakAreaReflection: "Weak-area reflection", pressureByTrack: "Pressure by track", radarIntro: "The radar emphasizes where mistakes, due reviews, and concept density are concentrating across the current course model.", moduleSequence: "Module sequence", modulePressureMap: "Module pressure map", modulePressureSubtitle: "Use this lane when you want to move module-by-module instead of by track.", priorityModules: "Priority modules", modulePressure: "Module pressure", moduleLaneIntro: "Use this module lane when you want a focused pass through one room before jumping across tracks.", moduleCode: "Module code", highYieldConcepts: "high-yield concepts", conceptPriorityLayer: "Concept priority layer", conceptPrioritySubtitle: "Filter by track to narrow the concepts that deserve the next deliberate review pass.", highPriorityQuizCards: "High-priority quiz cards", highPriorityTraps: "High-priority traps", highPriorityLongAnswers: "High-priority long answers", fastScoreProtection: "Fast score protection",
  projectBriefTitle: "Project brief", staticToAdaptiveTitle: "From static revision notes to adaptive exam preparation.", projectBriefIntro: "Modular Exam Revision Hub is a self-initiated, AI-ready web prototype that explores how learning-science principles and machine-learning-ready data structures can support more structured, interactive, and diagnosable exam preparation.", openPrototype: "Open prototype", viewPrintablePack: "View printable pack", positioning: "Positioning", prototype: "Prototype", conceptToDemoWorkflow: "Concept-to-demo workflow", data: "Data", synthetic: "Synthetic", noRealCourseMaterials: "No real course materials", architecture: "Architecture", modular: "Modular", replaceableCoursePacks: "Course packs can be replaced", extension: "Extension", aiReady: "AI-ready", ragIngestionPath: "RAG ingestion path", motivation: "Motivation", whyPrototypeExists: "Why this prototype exists", whyPrototypeExistsSubtitle: "Many students revise from scattered slides, notes, screenshots, and past mistakes. Generic AI study tools can generate content, but they often do not organise the whole exam workflow into a clear revision system.", learningScienceLayer: "Learning-science layer", learningScienceLayerText: "The review flow is informed by spaced repetition, active recall, cognitive-load reduction, and mistake-based metacognitive review. The goal is to move users from passive reading to structured recall.", mlReadyLayer: "ML-ready layer", mlReadyLayerText: "The content and interaction model is designed so future quiz attempts, confidence signals, review intervals, and mistake patterns can support knowledge tracing and cognitive diagnosis.", currentMvp: "Current MVP", mvpTitle: "What the rough prototype already demonstrates", mvpSubtitle: "The current version is intentionally lightweight. It uses structured synthetic content and focuses on showing the product logic, interface structure, and iteration path.", aiExtensionRoadmap: "AI extension roadmap", genuinelyInteractiveTitle: "How this can become genuinely interactive", genuinelyInteractiveSubtitle: "The safest next step is not to claim that the system trains a new model, but to connect the frontend with LLM/RAG-based course-content ingestion and personalised review generation.",
  mvpItem1: "Course/module selection with replaceable synthetic content packs", mvpItem2: "Concept cards, active-recall quizzes, common-trap cards, formula practice, and figure recognition", mvpItem3: "Mistake book, spaced-review queue, priority dashboard, and printable review sheets", mvpItem4: "LocalStorage-based prototype learning records for quick iteration without backend setup", roadmapItem1: "LLM/RAG-based course-content ingestion from user-provided materials", roadmapItem2: "Automatic generation of concept objects, quizzes, traps, formulas, figures, and long-answer prompts", roadmapItem3: "Knowledge tracing and cognitive-diagnosis layer based on quiz attempts and mistake patterns", roadmapItem4: "Backend/API integration for persistent user records and multi-course management",
  printableCheatSheetTitle: "Printable cheat sheet", printableCheatSheetSubtitle: "Compact exam synthesis. Use the browser Print button and choose Save as PDF.", syntheticDemoLearningScience: "Synthetic demo - Learning science / AI-ready revision prototype", generatedFromModules: "Generated from modular content packs", courseEvolution: "Course evolution", lastThirtyLines: "Last 30-minute lines", coreConcepts: "Core concepts", wrong: "Wrong", correctLabel: "Correct", why: "Why", highProbabilityLongAnswers: "High-probability long answers", groupedByModule: "grouped by module", formulasGroupedByModule: "formulas grouped by module.", answersGroupedByModule: "answer templates grouped by module.", quizGroupedByModule: "quiz items grouped by module.", trapsGroupedByModule: "traps grouped by module.", keywords: "Keywords", answerKey: "Answer key", seeExplanation: "See explanation", questionPagesFirst: "Print question pages first, then answer key.", wrongCorrectionWhy: "Wrong statement → correction → why.",
  pageNotFoundTitle: "Page not found", pageNotFoundBody: "This revision room does not exist. Return to the overview.", backToOverview: "Back to overview"
});



Object.assign(uiText.zh, {
  syntheticDemoData: "合成演示数据", learningScience: "学习科学", cognitiveDiagnosis: "认知诊断", prototypeEngineering: "原型工程", personalizedReview: "个性化复习", researchExtension: "研究扩展", aiReadyContentModel: "可接入人工智能的内容模型", allTracks: "全部路径", dueItemQueue: "到期复习队列", examWeight: "考试权重", formulaAnchors: "公式锚点", longFormReview: "长答案复习", longAnswers: "长答案", readTheseAloud: "大声读这些", examNote: "考试提示", example: "示例", wrongTimes: "错误 ×", openModuleRoom: "打开模块房间"
});
Object.assign(uiText.mix, {
  syntheticDemoData: "Synthetic demo data", learningScience: "Learning science", cognitiveDiagnosis: "Cognitive diagnosis", prototypeEngineering: "Prototype engineering", personalizedReview: "Personalized review", researchExtension: "Research extension", aiReadyContentModel: "AI-ready content model", allTracks: "All tracks", dueItemQueue: "Due-item queue", examWeight: "Exam weight", formulaAnchors: "Formula anchors", longFormReview: "Long-form review", longAnswers: "Long answers", readTheseAloud: "Read these aloud", examNote: "Exam note", example: "Example", wrongTimes: "wrong ×", openModuleRoom: "Open module room"
});
Object.assign(uiText.en, {
  syntheticDemoData: "Synthetic demo data", learningScience: "Learning science", cognitiveDiagnosis: "Cognitive diagnosis", prototypeEngineering: "Prototype engineering", personalizedReview: "Personalized review", researchExtension: "Research extension", aiReadyContentModel: "AI-ready content model", allTracks: "All tracks", dueItemQueue: "Due-item queue", examWeight: "Exam weight", formulaAnchors: "Formula anchors", longFormReview: "Long-form review", longAnswers: "Long answers", readTheseAloud: "Read these aloud", examNote: "Exam note", example: "Example", wrongTimes: "wrong ×", openModuleRoom: "Open module room"
});



Object.assign(uiText.zh, {
  homeEyebrow: "可接入人工智能的复习工作台", homeTitle: "先回忆，更快诊断，有目的地复习。", homeIntro: "这个公开演示使用合成课程内容，展示一个模块化、基于学习科学的复习流程：间隔重复、主动回忆、错题追踪、可打印复习包，以及可接入人工智能的内容模型。", modularCoursePacks: "模块化课程包", startTodaysReview: "开始今日复习", readProjectBrief: "阅读项目说明", todaysPulse: "今日脉搏", queueGuidance: "当你希望系统安排回忆顺序，而不是手动选择下一张卡片时，可使用该队列。", activeDays: "活跃天数", days: "天", countCardsReady: "张卡片待复习", weakSignals: "薄弱信号", compressionPass: "压缩复习", savedCards: "已收藏", systemKicker: "系统", knowledgeKicker: "知识", recallKicker: "回忆", riskKicker: "风险", expressionKicker: "表达", precisionKicker: "精确", memoryUnitsWithLinks: "带关联的记忆单元", recallFirstPrompts: "先回忆的提示", fastMarkProtection: "快速保护易失分点", structuredWritingPractice: "结构化写作练习", highContrastMathAnchors: "高对比度数学锚点", quickStudyActions: "快速学习行动", openThisLane: "打开这条通道", moduleArchitecture: "模块架构", moduleRooms: "模块房间", moduleRoomsSubtitle: "每个模块像一个独立学习舱：先看概念图，再进入记忆单元、测验、误区、公式、图表和长答案结构。", viewStudyPressure: "查看学习压力", moduleCards: "模块卡片", reviewLane: "复习通道", crossCuttingThemes: "跨模块主题", researchEngineeringTracks: "研究与工程路径", researchEngineeringSubtitle: "路径可以让你跨多个模块追踪同一想法，理解学习科学、诊断、人工智能流程和原型工程如何连接。", trackCards: "路径卡片", openTrackMap: "打开路径图", mistakeBookIntro: "当信心与正确率出现偏差时，使用错题本回放薄弱点。", reviewPageIntro: "用于在考试前快速压缩复习概念、长答案、公式、图表和常见误区。"
});
Object.assign(uiText.mix, {
  homeEyebrow: "AI-ready revision workspace", homeTitle: "Recall first. Diagnose faster. Review with intent.", homeIntro: "Public demo 使用 synthetic course content，展示 modular、learning-science-informed revision workflow：spaced repetition、active recall、mistake tracking、printable packs，以及 AI-ready content model。", modularCoursePacks: "Modular course packs", startTodaysReview: "Start today’s review", readProjectBrief: "Read project brief", todaysPulse: "Today’s pulse", queueGuidance: "当你希望 system sequence recall，而不是手动决定 next card 时，使用 queue。", activeDays: "Active days", days: "days", countCardsReady: "cards ready", weakSignals: "Weak signals", compressionPass: "Compression pass", savedCards: "Saved cards", systemKicker: "System", knowledgeKicker: "Knowledge", recallKicker: "Recall", riskKicker: "Risk", expressionKicker: "Expression", precisionKicker: "Precision", memoryUnitsWithLinks: "Memory units with links", recallFirstPrompts: "Recall-first prompts", fastMarkProtection: "Fast mark protection", structuredWritingPractice: "Structured writing practice", highContrastMathAnchors: "High-contrast math anchors", quickStudyActions: "Quick study actions", openThisLane: "Open this lane", moduleArchitecture: "Module architecture", moduleRooms: "Module rooms", moduleRoomsSubtitle: "每个 module 像 self-contained study chamber：concept map first，然后 memory units、quiz、traps、formulas、figures 和 long-answer structure。", viewStudyPressure: "View study pressure", moduleCards: "Module cards", reviewLane: "Review lane", crossCuttingThemes: "Cross-cutting themes", researchEngineeringTracks: "Research and engineering tracks", researchEngineeringSubtitle: "Tracks 让你跨 modules 追踪同一 idea，理解 learning science、diagnosis、AI workflow 和 prototype engineering 的连接。", trackCards: "Track cards", openTrackMap: "Open track map", mistakeBookIntro: "Use the mistake book when confidence and correctness drift apart.", reviewPageIntro: "Use this page to compress concepts, long answers, formulas, figures, and traps before an exam."
});
Object.assign(uiText.en, {
  homeEyebrow: "AI-ready revision workspace", homeTitle: "Recall first. Diagnose faster. Review with intent.", homeIntro: "This public demo uses synthetic course content to show a modular, learning-science-informed revision workflow: spaced repetition, active recall, mistake tracking, printable review packs, and an AI-ready content model.", modularCoursePacks: "Modular course packs", startTodaysReview: "Start today’s review", readProjectBrief: "Read project brief", todaysPulse: "Today’s pulse", queueGuidance: "Use the queue when you want the system to sequence recall, rather than manually deciding the next card.", activeDays: "Active days", days: "days", countCardsReady: "cards ready", weakSignals: "Weak signals", compressionPass: "Compression pass", savedCards: "Saved cards", systemKicker: "System", knowledgeKicker: "Knowledge", recallKicker: "Recall", riskKicker: "Risk", expressionKicker: "Expression", precisionKicker: "Precision", memoryUnitsWithLinks: "Memory units with links", recallFirstPrompts: "Recall-first prompts", fastMarkProtection: "Fast mark protection", structuredWritingPractice: "Structured writing practice", highContrastMathAnchors: "High-contrast math anchors", quickStudyActions: "Quick study actions", openThisLane: "Open this lane", moduleArchitecture: "Module architecture", moduleRooms: "Module rooms", moduleRoomsSubtitle: "Each module acts like a self-contained study chamber: concept map first, then memory units, then quiz, traps, formulas, figures, and long-answer structure.", viewStudyPressure: "View study pressure", moduleCards: "Module cards", reviewLane: "Review lane", crossCuttingThemes: "Cross-cutting themes", researchEngineeringTracks: "Research and engineering tracks", researchEngineeringSubtitle: "Tracks let you follow one idea across multiple modules, which is useful when you want to understand how learning science, diagnosis, AI workflow, and prototype engineering connect.", trackCards: "Track cards", openTrackMap: "Open track map", mistakeBookIntro: "Use the mistake book when confidence and correctness have drifted apart.", reviewPageIntro: "Use this page to compress concepts, long answers, formulas, figures, and common traps before an exam."
});



Object.assign(uiText.zh, {
  figurePageTitle: "图表识别", figurePageIntro: "训练“我正在看什么？”的能力，用于识别图示、复习循环、诊断循环、人工智能流程和系统架构图。", figureFilters: "图表筛选", figuresShown: "个图表", searchFiguresPlaceholder: "搜索图表，例如复习循环、诊断、检索增强、架构", allModules: "全部模块", visualDeck: "视觉卡组", recognitionBeforeExplanation: "先识别，再解释", visualDeckSubtitle: "先尝试根据视觉线索识别图表，再阅读识别问题和相关概念标签。", noMatchingFigures: "没有匹配的图表", broaderSearchReset: "请尝试更宽泛的搜索词，或重置筛选条件。",
  formulaPageTitle: "数学锚点", formulaPageIntro: "公式使用 KaTeX 渲染，并可查看公式源代码、变量、示例和考试提示。", startFormulaPractice: "开始公式练习", filterFormulas: "筛选公式", formulasShown: "个公式", searchFormulasPlaceholder: "搜索公式，例如遗忘曲线、掌握度、余弦、优先级",
  trapWall: "误区墙", trapsPageIntro: "当你觉得自己理解了概念、但仍容易掉进常见设计或推理错误时，使用这个页面。", filterTraps: "筛选误区", trapsShown: "个误区", searchTrapsPlaceholder: "搜索误区，例如过度声称、来源约束、被动阅读", commonMistakes: "常见错误",
  globalSearch: "全局搜索", globalSearchTitle: "查找概念、误区、测验和答案", globalSearchIntro: "搜索由模块化内容索引生成。", searchContentPlaceholder: "试试：间隔重复、认知诊断、检索增强、模块化结构", revisionSynthesisPage: "复习综合页", compressedReviewBuilt: "基于模块化课程内容和复习补丁生成的压缩复习。", systemEvolutionMap: "系统演化图", bigPicture: "总体图景", coreTopics: "核心主题", jumpList: "跳转列表", calculationSheet: "公式表", avoidCommonDesignErrors: "避免常见设计错误",
  allReviewTypes: "全部复习类型", quizOnly: "仅测验", trapsOnly: "仅误区", formulasOnly: "仅公式", figuresOnly: "仅图表", longAnswersOnly: "仅长答案", queueControls: "队列控制", cardsShown: "张卡片", dueSavedReviews: "条到期复习记录", scheduleAgain: "安排重来", scheduleGood: "安排掌握", scheduleEasy: "安排简单", lastRating: "上次：",
  trackNotFound: "未找到路径", noTrackExistsFor: "没有找到对应路径：", track: "路径", trackPath: "路径路线", modulesInvolved: "涉及模块", problemSolutionMap: "问题 → 解决方案图", whyEachMethodAppears: "为什么出现这些方法", problem: "问题", solution: "解决方案", trackConcepts: "路径概念", trackTraps: "路径误区", highValueMistakes: "高价值错误"
});
Object.assign(uiText.mix, {
  figurePageTitle: "Figure recognition", figurePageIntro: "训练“what am I looking at?”能力，用于 diagrams、review cycles、diagnostic loops、AI workflows 和 system architecture figures。", figureFilters: "Figure filters", figuresShown: "figures", searchFiguresPlaceholder: "Search figures, e.g. review cycle, diagnosis, RAG, architecture", allModules: "All modules", visualDeck: "Visual deck", recognitionBeforeExplanation: "Recognition before explanation", visualDeckSubtitle: "先从 visual cue 识别 figure，再读 recognition question 和 related concept tags。", noMatchingFigures: "No matching figures", broaderSearchReset: "Try a broader search term or reset filters.",
  formulaPageTitle: "Math anchors", formulaPageIntro: "Formulas 使用 KaTeX 渲染，并可查看 LaTeX source、variables、examples 和 exam notes。", startFormulaPractice: "Start formula practice", filterFormulas: "Filter formulas", formulasShown: "formulas shown", searchFormulasPlaceholder: "Search formulas, e.g. forgetting curve, mastery, cosine, priority",
  trapWall: "Trap wall", trapsPageIntro: "当你觉得自己 understand the idea，但仍容易掉进 design/reasoning mistakes 时使用这个页面。", filterTraps: "Filter traps", trapsShown: "traps shown", searchTrapsPlaceholder: "Search traps, e.g. overclaim, grounding, passive reading", commonMistakes: "Common mistakes",
  globalSearch: "Global search", globalSearchTitle: "Find concepts, traps, quiz, and answers", globalSearchIntro: "Search 由 modular content index 构建。", searchContentPlaceholder: "Try: spaced repetition, cognitive diagnosis, RAG, modular schema", revisionSynthesisPage: "Revision synthesis page", compressedReviewBuilt: "Compressed review built from modular course content and review patches.", systemEvolutionMap: "System evolution map", bigPicture: "Big picture", coreTopics: "Core topics", jumpList: "Jump list", calculationSheet: "Calculation sheet", avoidCommonDesignErrors: "Avoid common design errors",
  allReviewTypes: "All review types", quizOnly: "Quiz only", trapsOnly: "Traps only", formulasOnly: "Formulas only", figuresOnly: "Figures only", longAnswersOnly: "Long answers only", queueControls: "Queue controls", cardsShown: "cards shown", dueSavedReviews: "due saved reviews", scheduleAgain: "Schedule Again", scheduleGood: "Schedule Good", scheduleEasy: "Schedule Easy", lastRating: "last:",
  trackNotFound: "Track not found", noTrackExistsFor: "No track exists for", track: "Track", trackPath: "Track path", modulesInvolved: "Modules involved", problemSolutionMap: "Problem → solution map", whyEachMethodAppears: "Why each method appears", problem: "Problem", solution: "Solution", trackConcepts: "Track concepts", trackTraps: "Track traps", highValueMistakes: "High-value mistakes"
});
Object.assign(uiText.en, {
  figurePageTitle: "Figure recognition", figurePageIntro: "Train the “what am I looking at?” skill for diagrams, review cycles, diagnostic loops, AI workflows, and system architecture figures.", figureFilters: "Figure filters", figuresShown: "figures", searchFiguresPlaceholder: "Search figures, e.g. review cycle, diagnosis, RAG, architecture", allModules: "All modules", visualDeck: "Visual deck", recognitionBeforeExplanation: "Recognition before explanation", visualDeckSubtitle: "Try to identify the figure from the visual cue first. Then read the recognition question and related concept tags.", noMatchingFigures: "No matching figures", broaderSearchReset: "Try a broader search term or reset filters.",
  formulaPageTitle: "Math anchors", formulaPageIntro: "Formulas are rendered with KaTeX, with optional LaTeX source, variables, examples, and exam notes.", startFormulaPractice: "Start formula practice", filterFormulas: "Filter formulas", formulasShown: "formulas shown", searchFormulasPlaceholder: "Search formulas, e.g. forgetting curve, mastery, cosine, priority",
  trapWall: "Trap wall", trapsPageIntro: "Use this page when you feel you understand the idea but still fall into common design or reasoning mistakes.", filterTraps: "Filter traps", trapsShown: "traps shown", searchTrapsPlaceholder: "Search traps, e.g. overclaim, grounding, passive reading", commonMistakes: "Common mistakes",
  globalSearch: "Global search", globalSearchTitle: "Find concepts, traps, quiz, and answers", globalSearchIntro: "Search is built from the modular content index.", searchContentPlaceholder: "Try: spaced repetition, cognitive diagnosis, RAG, modular schema", revisionSynthesisPage: "Revision synthesis page", compressedReviewBuilt: "Compressed review built from modular course content and review patches.", systemEvolutionMap: "System evolution map", bigPicture: "Big picture", coreTopics: "Core topics", jumpList: "Jump list", calculationSheet: "Calculation sheet", avoidCommonDesignErrors: "Avoid common design errors",
  allReviewTypes: "All review types", quizOnly: "Quiz only", trapsOnly: "Traps only", formulasOnly: "Formulas only", figuresOnly: "Figures only", longAnswersOnly: "Long answers only", queueControls: "Queue controls", cardsShown: "cards shown", dueSavedReviews: "due saved reviews", scheduleAgain: "Schedule Again", scheduleGood: "Schedule Good", scheduleEasy: "Schedule Easy", lastRating: "last:",
  trackNotFound: "Track not found", noTrackExistsFor: "No track exists for", track: "Track", trackPath: "Track path", modulesInvolved: "Modules involved", problemSolutionMap: "Problem → solution map", whyEachMethodAppears: "Why each method appears", problem: "Problem", solution: "Solution", trackConcepts: "Track concepts", trackTraps: "Track traps", highValueMistakes: "High-value mistakes"
});



Object.assign(uiText.zh, { renderedFormulaFor: "渲染公式：", showVariablesExample: "显示变量 / 示例", hideVariables: "隐藏变量", showLatex: "显示 LaTeX", hideLatex: "隐藏 LaTeX", revealAnswer: "揭示答案", lower: "较少", higher: "较多", studyHeatmap: "学习活动热力图", searchContent: "搜索内容", results: "个结果", spacedReviewTitle: "今日回忆队列", spacedReviewIntro: "优先呈现错误答案、到期复习项目和高优先级内容。使用重来、困难、掌握、简单来安排下一轮复习。", showPreviousCard: "显示上一张卡片", showNextCard: "显示下一张卡片", backToCoverFlow: "返回卡片轨道", coverFlow: "卡片轨道", coverflowBrowseHint: "滚轮、滑动或箭头按钮可浏览。", coverflowBackHint: "使用返回按钮回到卡片轨道。" });
Object.assign(uiText.mix, { renderedFormulaFor: "Rendered formula for", showVariablesExample: "Show variables / example", hideVariables: "Hide variables", showLatex: "Show LaTeX", hideLatex: "Hide LaTeX", revealAnswer: "Reveal answer", lower: "Lower", higher: "Higher", studyHeatmap: "Study activity heatmap", searchContent: "Search content", results: "results", spacedReviewTitle: "Today’s recall queue", spacedReviewIntro: "Prioritizes wrong answers、due review items 和 high-priority review content。Use Again / Hard / Good / Easy to schedule the next pass。", showPreviousCard: "Show previous card", showNextCard: "Show next card", backToCoverFlow: "Back to cover flow", coverFlow: "Cover flow", coverflowBrowseHint: "Wheel, swipe, or use arrow buttons to browse.", coverflowBackHint: "Use Back to return to the cover flow rail." });
Object.assign(uiText.en, { renderedFormulaFor: "Rendered formula for", showVariablesExample: "Show variables / example", hideVariables: "Hide variables", showLatex: "Show LaTeX", hideLatex: "Hide LaTeX", revealAnswer: "Reveal answer", lower: "Lower", higher: "Higher", studyHeatmap: "Study activity heatmap", searchContent: "Search content", results: "results", spacedReviewTitle: "Today’s recall queue", spacedReviewIntro: "Prioritizes wrong answers, due review items, and high-priority review content. Use Again / Hard / Good / Easy to schedule the next pass.", showPreviousCard: "Show previous card", showNextCard: "Show next card", backToCoverFlow: "Back to cover flow", coverFlow: "Cover flow", coverflowBrowseHint: "Wheel, swipe, or use the arrow buttons to browse.", coverflowBackHint: "Use Back to return to the cover flow rail." });



Object.assign(uiText.zh, {
  practiceCards: "张练习卡", allModes: "全部模式", identifyFigure: "识别图表", visualCueRecall: "视觉线索回忆", expectedRecallDirection: "预期回忆方向", explainConceptShown: "解释图中展示的概念。", coverTitleMentally: "先在心里遮住标题。说出这个图在考查什么，再揭示答案。", iRecognizedIt: "我识别出来了", reviewAgain: "再次复习", figurePracticeTitle: "图表练习模式", figurePracticeIntro: "针对图表进行主动回忆：先识别图表，再回忆关键视觉线索，最后回答识别题。", practiceFilters: "练习筛选", searchFigurePracticePlaceholder: "搜索图表练习，例如复习循环、检索增强、架构",
  formulaPracticeTitle: "公式练习模式", formulaPracticeIntro: "用主动回忆代替反复阅读。先尝试记住公式，再揭示渲染结果。", formulaRecall: "公式回忆", allPracticeTypes: "全部练习类型", variableMeaning: "变量含义", examNoteType: "考试提示", searchFormulaPracticePlaceholder: "搜索公式练习，例如遗忘曲线、掌握度、余弦", recallPause: "暂停 5–10 秒。先尝试说出或写出答案，再揭示。", iKnewIt: "我记住了", hideAnswer: "隐藏答案", hint: "提示", recallFormulaFor: "回忆公式：", whatDoesMean: "是什么意思：", recallExamNoteFor: "回忆考试提示：", recallFormulaHint: "先尝试记住结构，再揭示渲染公式。", variableMeaningHint: "揭示前，请先用自己的话说出含义。", examNoteHint: "这是该公式对应的记忆句。"
});
Object.assign(uiText.mix, {
  practiceCards: "practice cards", allModes: "All modes", identifyFigure: "Identify figure", visualCueRecall: "Visual cue recall", expectedRecallDirection: "Expected recall direction", explainConceptShown: "Explain the concept shown by the diagram.", coverTitleMentally: "Cover title mentally，先说出 diagram 在考查什么，再 reveal。", iRecognizedIt: "I recognized it", reviewAgain: "Review again", figurePracticeTitle: "Figure practice mode", figurePracticeIntro: "Active recall for diagrams：先 identify figure，再 recall visual cue，最后 answer recognition question。", practiceFilters: "Practice filters", searchFigurePracticePlaceholder: "Search figure practice, e.g. review cycle, RAG, architecture",
  formulaPracticeTitle: "Formula practice mode", formulaPracticeIntro: "Use active recall instead of rereading. Reveal formula only after trying to remember it.", formulaRecall: "Formula recall", allPracticeTypes: "All practice types", variableMeaning: "Variable meaning", examNoteType: "Exam note", searchFormulaPracticePlaceholder: "Search formula practice, e.g. forgetting curve, mastery, cosine", recallPause: "Pause 5–10 seconds. Try to say or write the answer before revealing.", iKnewIt: "I knew it", hideAnswer: "Hide answer", hint: "Hint", recallFormulaFor: "Recall the formula for", whatDoesMean: "What does this mean in", recallExamNoteFor: "What is the exam note for", recallFormulaHint: "Try to remember the structure first, then reveal the rendered formula.", variableMeaningHint: "Say the meaning in your own words before revealing.", examNoteHint: "This is the memory sentence attached to the formula."
});
Object.assign(uiText.en, {
  practiceCards: "practice cards", allModes: "All modes", identifyFigure: "Identify figure", visualCueRecall: "Visual cue recall", expectedRecallDirection: "Expected recall direction", explainConceptShown: "Explain the concept shown by the diagram.", coverTitleMentally: "Cover the title mentally. Say what this diagram is testing before revealing.", iRecognizedIt: "I recognized it", reviewAgain: "Review again", figurePracticeTitle: "Figure practice mode", figurePracticeIntro: "Active recall for diagrams. First identify the figure, then recall the key visual cue, then answer the recognition question.", practiceFilters: "Practice filters", searchFigurePracticePlaceholder: "Search figure practice, e.g. review cycle, RAG, architecture",
  formulaPracticeTitle: "Formula practice mode", formulaPracticeIntro: "Use active recall instead of just rereading. Reveal the rendered formula only after you try to remember it.", formulaRecall: "Formula recall", allPracticeTypes: "All practice types", variableMeaning: "Variable meaning", examNoteType: "Exam note", searchFormulaPracticePlaceholder: "Search formula practice, e.g. forgetting curve, mastery, cosine", recallPause: "Pause for 5–10 seconds. Try to say or write the answer before revealing.", iKnewIt: "I knew it", hideAnswer: "Hide answer", hint: "Hint", recallFormulaFor: "Recall the formula for", whatDoesMean: "What does this mean in", recallExamNoteFor: "What is the exam note for", recallFormulaHint: "Try to remember the structure first, then reveal the rendered formula.", variableMeaningHint: "Say the meaning in your own words before revealing.", examNoteHint: "This is the memory sentence attached to the formula."
});


Object.assign(uiText.zh, { recognitionQuestion: "识别题" });
Object.assign(uiText.mix, { recognitionQuestion: "Recognition question" });
Object.assign(uiText.en, { recognitionQuestion: "Recognition question" });


Object.assign(uiText.zh, { highYieldPanel: "高价值复习面板", grabThisPageFirst: "先抓这一页", mustKnow: "必须掌握", trapFocus: "误区重点", formulaFocus: "公式重点", figureFocus: "图表重点" });
Object.assign(uiText.mix, { highYieldPanel: "High-yield panel", grabThisPageFirst: "先抓这一页", mustKnow: "Must know", trapFocus: "Trap focus", formulaFocus: "Formula focus", figureFocus: "Figure focus" });
Object.assign(uiText.en, { highYieldPanel: "High-yield panel", grabThisPageFirst: "Grab this page first", mustKnow: "Must know", trapFocus: "Trap focus", formulaFocus: "Formula focus", figureFocus: "Figure focus" });


Object.assign(uiText.zh, { noItems: "暂无项目。" });
Object.assign(uiText.mix, { noItems: "No items." });
Object.assign(uiText.en, { noItems: "No items." });

function normalizeMode(mode) { return mode === "both" ? "mix" : (["zh", "mix", "en"].includes(mode) ? mode : "mix"); }
function readPath(obj, path) { return !obj || !path ? undefined : String(path).split(".").reduce((acc, key) => acc?.[key], obj); }
function isPlainObject(value) { return value && typeof value === "object" && !Array.isArray(value); }
function deepMerge(target = {}, patch = {}) { const out = Array.isArray(target) ? [...target] : { ...(target || {}) }; for (const [key, value] of Object.entries(patch || {})) { out[key] = isPlainObject(value) && isPlainObject(out[key]) ? deepMerge(out[key], value) : value; } return out; }

export function getLocalizedValue(item, field, mode = "mix", fallback) {
  const normalized = normalizeMode(mode);
  const base = fallback ?? readPath(item, field);
  const preferred = readPath(item?.i18n?.[normalized], field);
  const mix = readPath(item?.i18n?.mix, field) ?? readPath(item?.i18n?.both, field);
  const zh = readPath(item?.i18n?.zh, field);
  const en = readPath(item?.i18n?.en, field);
  if (normalized === "zh") return zh ?? mix ?? en ?? base ?? "";
  if (normalized === "en") return en ?? base ?? mix ?? zh ?? "";
  return preferred ?? mix ?? zh ?? en ?? base ?? "";
}

export function localizeItem(item, mode = "mix") {
  if (!item || typeof item !== "object") return item;
  const normalized = normalizeMode(mode);
  const localized = item.i18n?.[normalized] ?? item.i18n?.mix ?? item.i18n?.both ?? item.i18n?.zh;
  return localized ? deepMerge(item, localized) : item;
}

export function localizeContentTree(value, mode = "mix") {
  if (Array.isArray(value)) return value.map((item) => localizeContentTree(item, mode));
  if (!isPlainObject(value)) return value;
  const merged = localizeItem(value, mode);
  const out = { ...merged };
  for (const [key, child] of Object.entries(merged)) {
    if (key === "i18n") continue;
    if (Array.isArray(child) || isPlainObject(child)) out[key] = localizeContentTree(child, mode);
  }
  return out;
}

export function LanguageProvider({ children }) {
  const [rawMode, setRawMode] = useLocalStorage("modular-exam-revision-language-mode", "mix");
  const languageMode = normalizeMode(rawMode);
  const api = useMemo(() => ({
    languageMode,
    setLanguageMode: (mode) => setRawMode(normalizeMode(mode)),
    t: (item, field, fallback) => getLocalizedValue(item, field, languageMode, fallback),
    ui: (key) => uiText[languageMode]?.[key] ?? uiText.en[key] ?? key
  }), [languageMode, setRawMode]);
  return <LanguageContext.Provider value={api}>{children}</LanguageContext.Provider>;
}

export function useLanguage() { const ctx = useContext(LanguageContext); if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider"); return ctx; }
