function addI18n(items, translations) {
  return (items || []).map((item) => {
    const patch = translations[item.id];
    return patch ? { ...item, i18n: { ...(item.i18n || {}), ...patch } } : item;
  });
}

function addNestedI18n(items, translations, idField) {
  return (items || []).map((item) => {
    const id = item?.[idField] || item?.id || item?.section;
    const patch = translations[id];
    return patch ? { ...item, i18n: { ...(item.i18n || {}), ...patch } } : item;
  });
}

const lectureI18n = {
  w01: {
    zh: { title: "模块 01 — 学习科学基础", subtitle: "间隔重复、主动回忆、认知负荷和元认知复习。", mainQuestion: "复习系统如何把被动笔记转化为主动、按计划进行的学习任务？", visualMap: { title: "编码 → 回忆 → 诊断 → 安排复习", note: "本模块把学习科学原则连接到具体复习交互。" } },
    mix: { title: "Module 01 — Learning Science 基础", subtitle: "Spaced repetition、active recall、cognitive load 和 metacognitive review。", mainQuestion: "Revision system 如何把 passive notes 变成 active、scheduled learning tasks？", visualMap: { title: "Encode → Recall → Diagnose → Schedule", note: "本模块把 learning-science principles 连接到具体 revision interactions。" } }
  },
  w02: {
    zh: { title: "模块 02 — 认知诊断与学习记录", subtitle: "知识组件、掌握程度估计、信心和错误模式。", mainQuestion: "答题记录和错误如何成为诊断薄弱点的信号？", visualMap: { title: "尝试 → 证据 → 诊断 → 复习路径", note: "学习记录只有在关联到具体知识组件时才真正有用。" } },
    mix: { title: "Module 02 — Cognitive Diagnosis 与 Learning Records", subtitle: "Knowledge components、mastery estimates、confidence 和 mistake patterns。", mainQuestion: "Quiz attempts 和 mistakes 如何变成 diagnosing weak areas 的信号？", visualMap: { title: "Attempt → Evidence → Diagnosis → Review Path", note: "Learning record 只有绑定到 specific knowledge components 才真正有用。" } }
  },
  w03: {
    zh: { title: "模块 03 — AI-ready 内容导入", subtitle: "未来用于把用户材料转化为复习单元的 RAG/LLM 工作流。", mainQuestion: "上传材料如何变成结构化概念、测验、误区和解释？", visualMap: { title: "上传 → 切分 → 检索 → 生成 → 验证", note: "当前粗略演示使用合成数据；系统结构为后续 LLM/RAG 集成预留空间。" } },
    mix: { title: "Module 03 — AI-Ready Content Ingestion", subtitle: "面向 user-provided materials 的 future RAG/LLM workflow，可转成 review units。", mainQuestion: "Uploaded materials 如何变成 structured concepts、quizzes、traps 和 explanations？", visualMap: { title: "Upload → Chunk → Retrieve → Generate → Verify", note: "Rough demo 现在使用 synthetic data；architecture 保留后续 LLM/RAG integration 空间。" } }
  },
  w04: {
    zh: { title: "模块 04 — 原型系统与评估", subtitle: "模块化 schema、本地学习记录、仪表盘设计和部署流程。", mainQuestion: "如何把该原型同时作为网页系统和研究平台进行评估？", visualMap: { title: "课程包 → UI 卡片 → 学习记录 → 复习推荐", note: "模块化数据结构让演示更容易适配多个课程。" } },
    mix: { title: "Module 04 — Prototype System and Evaluation", subtitle: "Modular schema、local learning logs、dashboard design 和 deployment workflow。", mainQuestion: "Prototype 如何同时作为 web system 和 research platform 来 evaluation？", visualMap: { title: "Course Pack → UI Cards → Learning Log → Review Recommendation", note: "Modular data structure 让 demo 更容易适配 multiple courses。" } }
  }
};

const conceptI18n = {
  "spaced-repetition": {
    zh: { title: "间隔重复", shortDefinition: "一种在逐渐拉长的时间间隔后安排重复练习的复习策略。", overview: { definition: "间隔重复会在延迟一段时间后再次呈现学习项目，让学习者在记忆变弱之前练习回忆。", whyItMatters: "它解释了系统为什么需要维护到期日期和复习队列，而不是平等展示所有材料。", keyIdea: "复习时间安排是学习界面的一部分，而不是单独的提醒功能。" }, exam: { shortAnswer: "间隔重复会优先安排那些应在合适延迟后再次回忆的项目。" }, visual: { memoryCue: "不要只是重读；要在合适时间回来回忆。" } },
    mix: { title: "Spaced Repetition", shortDefinition: "一种在 increasing intervals 后安排 repeated practice 的 review strategy。", overview: { definition: "Spaced repetition 会在 delay 后再次呈现 learning item，让 recall 在记忆太弱之前发生。", whyItMatters: "它解释系统为什么需要 due dates 和 review queues，而不是平均展示所有材料。", keyIdea: "Review timing 是 learning interface 的一部分，不只是 reminder feature。" }, exam: { shortAnswer: "Spaced repetition 会优先安排适合再次 recall 的 items。" }, visual: { memoryCue: "不要只是 reread；要在 right time 回来 recall。" } }
  },
  "active-recall": {
    zh: { title: "主动回忆", shortDefinition: "学习者先提取答案，再查看答案的练习方法。", overview: { definition: "主动回忆把学习转化为提取任务，例如回答测验、解释概念或重构公式。", whyItMatters: "原型使用测验卡片、公式练习和长答案提示，因为提取比被动阅读更能产生诊断信息。", keyIdea: "系统先提问，再解释。" }, exam: { shortAnswer: "主动回忆要求学习者先提取信息，再检查解释。" }, visual: { memoryCue: "先问题，后解释。" } },
    mix: { title: "Active Recall", shortDefinition: "Learner 先 retrieve answer，再看到答案的 practice method。", overview: { definition: "Active recall 把 study 变成 retrieval task，例如 answer quiz、explain concept 或 reconstruct formula。", whyItMatters: "Prototype 使用 quiz cards、formula practice 和 long-answer prompts，因为 retrieval 比 passive reading 更 diagnostic。", keyIdea: "System asks before it explains。" }, exam: { shortAnswer: "Active recall 要求 learner 在查看 explanation 前先 retrieve information。" }, visual: { memoryCue: "Question first, explanation second。" } }
  },
  "cognitive-load": {
    zh: { title: "认知负荷降低", shortDefinition: "在复习过程中减少不必要心理负担的设计原则。", overview: { definition: "认知负荷降低意味着界面应让下一步行动清晰，并避免一次展示过多无关细节。", whyItMatters: "如果每个功能都争夺注意力，复习仪表盘会变得混乱。", keyIdea: "卡片、标签页、筛选器和简洁标签让注意力集中在一次复习决策上。" }, exam: { shortAnswer: "系统通过模块化卡片、分组页面和聚焦复习流程降低认知负荷。" }, visual: { memoryCue: "少一些噪音，下一步更清楚。" } },
    mix: { title: "Cognitive Load Reduction", shortDefinition: "在 review 中减少 unnecessary mental effort 的 design principle。", overview: { definition: "Cognitive load reduction 意味着 interface 应让 next action 明确，并避免同时展示太多 unrelated details。", whyItMatters: "如果每个 feature 都 competing for attention，revision dashboard 会变得 confusing。", keyIdea: "Cards、tabs、filters 和 concise labels 让 attention 集中在 one review decision。" }, exam: { shortAnswer: "系统通过 modular cards、grouped pages 和 focused review flows 降低 cognitive load。" }, visual: { memoryCue: "Less noise, clearer next action。" } }
  },
  "metacognitive-review": {
    zh: { title: "元认知复习", shortDefinition: "帮助学习者监控自己知道什么、不知道什么和反复错什么的复习。", overview: { definition: "元认知复习通过错误记录、信心检查和反思提示让薄弱区域可见。", whyItMatters: "错题本和优先级仪表盘只有在帮助学习者决定下一步复习内容时才更有意义。", keyIdea: "好的系统不仅记录答案，也记录不确定性和重复模式。" }, exam: { shortAnswer: "元认知复习帮助学习者看到自己的薄弱区域并调整学习计划。" }, visual: { memoryCue: "知道自己知道什么，也注意自己错在哪里。" } },
    mix: { title: "Metacognitive Review", shortDefinition: "帮助 learner monitor 知道什么、不知道什么和 repeatedly miss 什么的 review。", overview: { definition: "Metacognitive review 使用 mistake records、confidence checks 和 reflection prompts 让 weak areas 可见。", whyItMatters: "Mistake book 和 priority dashboard 只有在帮助 learner 决定 next review 时才更有意义。", keyIdea: "Good system 不只记录 answers，也记录 uncertainty 和 repeated patterns。" }, exam: { shortAnswer: "Metacognitive review 帮助 learners 看到 weak areas 并调整 study plan。" }, visual: { memoryCue: "Know what you know; notice what you miss。" } }
  },
  "knowledge-component": {
    zh: { title: "知识组件", shortDefinition: "学习者应掌握的一个小技能或概念。", overview: { definition: "知识组件可以是公式、概念、步骤或识别技能等学习单元。", whyItMatters: "当每道题或每个错误都能关联到一个或多个知识组件时，诊断才更有用。", keyIdea: "不要只记录答错了，还要记录它指向哪项技能。" }, exam: { shortAnswer: "知识组件把学习活动连接到具体薄弱区域。" }, visual: { memoryCue: "错误背后通常有一个具体技能点。" } },
    mix: { title: "Knowledge Component", shortDefinition: "Learner 需要 master 的小 skill 或 concept。", overview: { definition: "Knowledge component 是 formula、concept、procedure 或 recognition skill 这样的 learning unit。", whyItMatters: "当 quiz 或 mistake 能 linked to knowledge components 时，diagnosis 更有用。", keyIdea: "不要只记录 wrong answer；记录它指向哪个 skill。" }, exam: { shortAnswer: "Knowledge components 把 learning activities 连接到 specific weak areas。" }, visual: { memoryCue: "A mistake usually points to a skill。" } }
  },
  "mastery-estimate": {
    zh: { title: "掌握程度估计", shortDefinition: "对学习者理解某个知识组件程度的暂定估计。", overview: { definition: "掌握程度估计可以根据答题正确性、复习评分、时间间隔和重复错误更新。", whyItMatters: "它把原始交互数据连接到个性化推荐。", keyIdea: "掌握程度是概率性的，不应被当成单次考试分数。" }, exam: { shortAnswer: "掌握程度估计总结了学习者可能理解某概念的证据。" }, visual: { memoryCue: "掌握程度是估计，不是绝对标签。" } },
    mix: { title: "Mastery Estimate", shortDefinition: "对 learner 理解某个 knowledge component 程度的 tentative estimate。", overview: { definition: "Mastery estimate 可由 quiz correctness、review ratings、time gaps 和 repeated mistakes 更新。", whyItMatters: "它把 raw interactions 连接到 personalized recommendations。", keyIdea: "Mastery 是 probabilistic，不能当成 one test score。" }, exam: { shortAnswer: "Mastery estimate summarizes 关于 learner likely understanding 的 evidence。" }, visual: { memoryCue: "Mastery is an estimate, not a fixed label。" } }
  },
  "mistake-pattern": {
    zh: { title: "错误模式", shortDefinition: "揭示特定误解的一类重复错误。", overview: { definition: "错误模式比单次错误更有信息量，因为它暗示稳定混淆或缺失技能。", whyItMatters: "错题本可以归类重复误区，引导有针对性的复习。", keyIdea: "模式把错误答案转化为复习决策。" }, exam: { shortAnswer: "错误模式是与特定概念或技能相关的重复错误。" }, visual: { memoryCue: "一次错误是事件，重复错误是信号。" } },
    mix: { title: "Mistake Pattern", shortDefinition: "揭示 specific misunderstanding 的 repeated error type。", overview: { definition: "Mistake pattern 比 single wrong answer 更 informative，因为它暗示 stable confusion 或 missing skill。", whyItMatters: "Mistake book 可以 group repeated traps，引导 targeted review。", keyIdea: "Patterns turn wrong answers into review decisions。" }, exam: { shortAnswer: "Mistake pattern 是 linked to specific concept or skill 的 repeated error。" }, visual: { memoryCue: "One error is an event; repeated errors are signals。" } }
  },
  "confidence-calibration": {
    zh: { title: "信心校准", shortDefinition: "学习者的自信程度与实际正确程度之间的对齐。", overview: { definition: "信心校准比较自报确定性与实际答题表现或解释质量。", whyItMatters: "过度自信可能隐藏薄弱点，信心不足则可能浪费复习时间。", keyIdea: "未来系统可以在揭示答案前询问信心。" }, exam: { shortAnswer: "校准显示学习者信心是否匹配实际表现。" }, visual: { memoryCue: "信心只有与证据对照后才有意义。" } },
    mix: { title: "Confidence Calibration", shortDefinition: "Learner confidence 与 correctness 之间的 alignment。", overview: { definition: "Confidence calibration 比较 self-reported certainty 与 actual quiz performance 或 explanation quality。", whyItMatters: "Overconfidence 会隐藏 weak areas，underconfidence 会浪费 review time。", keyIdea: "Future system 可以在 reveal answers 前询问 confidence。" }, exam: { shortAnswer: "Calibration shows learner confidence 是否 matches actual performance。" }, visual: { memoryCue: "Confidence is useful only when checked against evidence。" } }
  },
  "content-ingestion": {
    zh: { title: "课程内容导入", shortDefinition: "把用户提供的材料转化为结构化复习项目的过程。", overview: { definition: "内容导入可包括解析笔记、切分文本、抽取概念和生成复习卡片。", whyItMatters: "它是静态原型走向真正互动式复习助手的未来桥梁。", keyIdea: "上传并不够；系统需要结构、可追溯性和验证。" }, exam: { shortAnswer: "内容导入把原始课程材料转化为结构化复习对象。" }, visual: { memoryCue: "原始笔记变成结构化学习对象。" } },
    mix: { title: "Course Content Ingestion", shortDefinition: "把 user-provided materials 转成 structured review items 的 process。", overview: { definition: "Content ingestion 包括 parsing notes、splitting text into chunks、extracting concepts 和 creating review cards。", whyItMatters: "它是 static prototype 与 genuinely interactive revision assistant 之间的 future bridge。", keyIdea: "Upload is not enough；system 需要 structure、traceability 和 verification。" }, exam: { shortAnswer: "Content ingestion converts raw course materials into structured review objects。" }, visual: { memoryCue: "Raw notes become structured learning objects。" } }
  },
  "rag-assistant": {
    zh: { title: "基于 RAG 的复习助手", shortDefinition: "使用检索到的课程语境进行回答和生成学习项目的助手。", overview: { definition: "检索增强生成会先检索相关来源片段，再生成解释、测验或总结。", whyItMatters: "它避免夸大为必须从零训练一个新模型。", keyIdea: "先检索和 grounding，再生成。" }, exam: { shortAnswer: "RAG 助手参考检索到的课程内容生成复习支持。" }, visual: { memoryCue: "先 retrieve，再 generate。" } },
    mix: { title: "RAG-Based Revision Assistant", shortDefinition: "使用 retrieved course-grounded context 来 answer 和 generate study items 的 assistant。", overview: { definition: "Retrieval-augmented generation 先 retrieve relevant source chunks，再 generate explanations、quizzes 或 summaries。", whyItMatters: "它避免 overclaim 项目需要 train a new model from scratch。", keyIdea: "Use retrieval and grounding before generation。" }, exam: { shortAnswer: "RAG assistant 参考 retrieved course content 生成 revision support。" }, visual: { memoryCue: "Retrieve first; generate second。" } }
  },
  "quiz-generation": {
    zh: { title: "AI 辅助测验生成", shortDefinition: "使用 AI 工作流从结构化学习材料中草拟测验题。", overview: { definition: "测验生成可以提出选择、判断和简答题，但输出应检查歧义和来源一致性。", whyItMatters: "它展示课程材料导入后，原型如何变得真正互动。", keyIdea: "生成题应作为可编辑的结构化数据保存，而不只是聊天输出。" }, exam: { shortAnswer: "当生成题有来源依据、可编辑并链接到概念时才有用。" }, visual: { memoryCue: "AI 起草；系统结构化并检查。" } },
    mix: { title: "AI-Assisted Quiz Generation", shortDefinition: "使用 AI workflow 从 structured learning materials 草拟 quiz questions。", overview: { definition: "Quiz generation 可以提出 multiple-choice、true/false 和 short-answer prompts，但需要检查 ambiguity 和 source alignment。", whyItMatters: "它展示 prototype 在 course materials ingested 后如何 genuinely interactive。", keyIdea: "Generated quizzes 应保存为 editable structured data，而不只是 chat output。" }, exam: { shortAnswer: "Generated quizzes 在 grounded、editable 并 linked to concepts 时才 useful。" }, visual: { memoryCue: "AI drafts; the system structures and checks。" } }
  },
  "grounding-guardrail": {
    zh: { title: "来源约束护栏", shortDefinition: "让生成的复习内容始终绑定到来源材料的安全机制。", overview: { definition: "来源约束护栏可要求来源片段、置信检查或人工审核，之后才把生成内容加入课程包。", whyItMatters: "教育工具不应编造事实或误导课程要求。", keyIdea: "没有来源，就不要作为高置信学习项目。" }, exam: { shortAnswer: "来源约束护栏减少无依据或误导性的生成复习项目。" }, visual: { memoryCue: "生成内容应能指回证据。" } },
    mix: { title: "Grounding Guardrail", shortDefinition: "让 generated review content 绑定到 source material 的 safeguard。", overview: { definition: "Grounding guardrail 可以要求 source chunks、confidence checks 或 human review，再加入 course pack。", whyItMatters: "Educational tools 不应 invent facts 或 misrepresent course requirements。", keyIdea: "No source, no high-confidence study item。" }, exam: { shortAnswer: "Grounding guardrails 减少 unsupported 或 misleading generated review items。" }, visual: { memoryCue: "Generated content should point back to evidence。" } }
  },
  "modular-schema": {
    zh: { title: "模块化课程 Schema", shortDefinition: "可复用的数据结构，覆盖模块、概念、测验、误区、公式、图表和答案。", overview: { definition: "模块化 schema 让每门课成为可替换内容包，而不是写死在网站里的文本。", whyItMatters: "它直接支持不同课程加载到同一复习系统。", keyIdea: "应用应读取课程数据，而不是固定的一门课页面。" }, exam: { shortAnswer: "模块化 schema 让同一界面支持多个课程。" }, visual: { memoryCue: "让课程数据可替换。" } },
    mix: { title: "Modular Course Schema", shortDefinition: "覆盖 modules、concepts、quizzes、traps、formulas、figures 和 answers 的 reusable data structure。", overview: { definition: "Modular schema 让每门 course 成为 replaceable content pack，而不是 hard-coded website text。", whyItMatters: "它直接支持 different courses 被 loaded into the same revision system。", keyIdea: "App should read course data, not be one fixed course page。" }, exam: { shortAnswer: "Modular schema lets the same interface support multiple courses。" }, visual: { memoryCue: "Make the course data swappable。" } }
  },
  "local-learning-log": {
    zh: { title: "本地学习记录", shortDefinition: "浏览器端保存测验尝试、复习评分、收藏和到期项目的记录。", overview: { definition: "粗略原型把用户进度保存在本地，以展示复习逻辑而无需后端。", whyItMatters: "它让原型可运行，同时把后端同步留作未来扩展。", keyIdea: "最小学习记录已足以支持原型中的错题和间隔复习。" }, exam: { shortAnswer: "本地学习记录在后端集成前支持 MVP 复习闭环。" }, visual: { memoryCue: "先本地原型，后续再扩展。" } },
    mix: { title: "Local Learning Log", shortDefinition: "浏览器端记录 quiz attempts、review ratings、bookmarks 和 due items。", overview: { definition: "Rough prototype 本地存储 user progress，以 demonstrate review logic，不需要 backend。", whyItMatters: "它允许 functional demo，同时把 backend synchronization 留作 future extension。", keyIdea: "Minimal log 已足够支撑 prototype 中的 mistakes 和 spaced review。" }, exam: { shortAnswer: "Local learning log supports an MVP review loop before backend integration。" }, visual: { memoryCue: "Prototype locally, scale later。" } }
  },
  "priority-dashboard": {
    zh: { title: "优先级仪表盘", shortDefinition: "根据优先级、错误和学习信号排序复习项目的仪表盘。", overview: { definition: "优先级仪表盘帮助学习者决定下一步复习什么，而不是平等浏览所有模块。", whyItMatters: "它把学习科学连接到界面设计和未来基于 ML 的推荐。", keyIdea: "仪表盘应让下一步复习行动变得明显。" }, exam: { shortAnswer: "优先级仪表盘会显示高价值概念、误区和测验以供复习。" }, visual: { memoryCue: "把很多项目转成一个下一步行动。" } },
    mix: { title: "Priority Dashboard", shortDefinition: "根据 priority、mistakes 和 learning signals 排序 review items 的 dashboard。", overview: { definition: "Priority dashboard 帮 learner decide what to review next，而不是 equally browsing all modules。", whyItMatters: "它连接 learning science、interface design 和 future ML-based recommendation。", keyIdea: "Dashboard should make next review action obvious。" }, exam: { shortAnswer: "Priority dashboard surfaces high-value concepts、traps 和 quizzes for review。" }, visual: { memoryCue: "Turn many items into one next action。" } }
  },
  "deployment-workflow": {
    zh: { title: "部署流程", shortDefinition: "从本地原型到可分享网页演示的简洁路径。", overview: { definition: "该原型通过验证后可以部署到 GitHub Pages、Vercel 或其他静态托管流程。", whyItMatters: "可分享构建让原型更容易被查看、测试和继续改进。", keyIdea: "有在线演示和干净仓库时，项目更容易被评审。" }, exam: { shortAnswer: "部署把本地构建变成他人可测试的可分享原型。" }, visual: { memoryCue: "Live demo 比描述传达更快。" } },
    mix: { title: "Deployment Workflow", shortDefinition: "从 local prototype 到 shareable web demo 的 simple path。", overview: { definition: "Prototype 可在 validation 后通过 GitHub Pages、Vercel 或 static hosting workflow 部署。", whyItMatters: "Shareable build 让 prototype 更容易 review、test 和 iterate。", keyIdea: "有 live demo 和 clean repository，project 更容易 review。" }, exam: { shortAnswer: "Deployment turns local build into shareable prototype that others can test。" }, visual: { memoryCue: "A live demo communicates faster than a description。" } }
  }
};

const quizI18n = {
  "q-spaced-repetition": { zh: { question: "哪个功能最直接支持间隔重复？", options: ["静态 PDF 导出", "到期复习队列", "随机颜色主题", "很长的首页"], correctAnswers: ["到期复习队列"], explanation: "到期复习队列会按间隔安排项目进行重复回忆。" }, mix: { question: "哪个 feature 最直接支持 spaced repetition？", options: ["Static PDF export", "Due review queue", "Random color theme", "Long landing page"], correctAnswers: ["Due review queue"], explanation: "Due review queue 会按 intervals 安排 repeated recall。" } },
  "q-active-recall": { zh: { question: "哪种交互最能代表主动回忆？", options: ["先显示答案", "把所有笔记读两遍", "先做题再看解释", "只浏览目录"], correctAnswers: ["先做题再看解释"], explanation: "主动回忆要求先提取，再获得反馈。" }, mix: { question: "Active recall 最适合由哪种 interaction 表示？", options: ["Reveal the answer first", "Read all notes twice", "Try a quiz before seeing the explanation", "Only browse the table of contents"], correctAnswers: ["Try a quiz before seeing the explanation"], explanation: "Active recall requires retrieval before feedback。" } },
  "q-knowledge-component": { zh: { question: "为什么一道测验题应关联到知识组件？", options: ["让界面更彩色", "识别回答背后的薄弱技能", "不再需要解释", "避免记录尝试"], correctAnswers: ["识别回答背后的薄弱技能"], explanation: "概念链接让诊断和定向复习成为可能。" }, mix: { question: "为什么 quiz item 应 linked to a knowledge component？", options: ["To make the UI colorful", "To identify the weak skill behind a response", "To remove the need for explanations", "To avoid tracking attempts"], correctAnswers: ["To identify the weak skill behind a response"], explanation: "Concept linkage makes diagnosis and review targeting possible。" } },
  "q-confidence-calibration": { zh: { question: "学习者答错但非常自信，系统应如何判断？", options: ["忽略结果", "标记为已掌握", "视为高价值复习信号", "删除题目"], correctAnswers: ["视为高价值复习信号"], explanation: "高信心错误通常揭示隐藏误解。" }, mix: { question: "Learner wrong but highly confident，system 应 infer 什么？", options: ["Ignore the result", "Mark as mastered", "Treat it as a high-value review signal", "Delete the question"], correctAnswers: ["Treat it as a high-value review signal"], explanation: "High-confidence errors often reveal hidden misconceptions。" } },
  "q-rag-vs-finetuning": { zh: { question: "对于轻量课程助手原型，为什么描述 RAG 通常比训练新 LLM 更安全？", options: ["RAG 不需要课程材料", "RAG 可利用检索到的来源语境，而不声称训练模型", "RAG 会自动消除所有错误", "RAG 只是前端功能"], correctAnswers: ["RAG 可利用检索到的来源语境，而不声称训练模型"], explanation: "RAG 支持基于来源的生成，同时避免夸大模型训练。" }, mix: { question: "对于 lightweight course assistant prototype，为什么 RAG 比 training a new LLM 更安全？", options: ["RAG requires no course materials", "RAG can use retrieved source context without claiming model training", "RAG removes all errors automatically", "RAG is only a frontend feature"], correctAnswers: ["RAG can use retrieved source context without claiming model training"], explanation: "RAG supports source-grounded generation without overstating model training。" } },
  "q-grounding": { zh: { question: "哪条规则最能描述来源约束护栏？", options: ["无来源，不作为高置信项目", "永远信任生成文本", "禁用人工审核", "只保存原始聊天输出"], correctAnswers: ["无来源，不作为高置信项目"], explanation: "来源约束让生成学习内容与证据绑定。" }, mix: { question: "哪条 rule 最适合描述 grounding guardrail？", options: ["No source, no high-confidence item", "Always trust generated text", "Disable human review", "Store only raw chat output"], correctAnswers: ["No source, no high-confidence item"], explanation: "Grounding keeps generated study content tied to evidence。" } },
  "q-modular-schema": { zh: { question: "模块化课程 schema 的主要好处是什么？", options: ["让每门课都写死", "让同一界面加载不同课程包", "不再需要数据验证", "阻止部署"], correctAnswers: ["让同一界面加载不同课程包"], explanation: "当内容以可替换的结构化数据保存时，系统就变成课程无关。" }, mix: { question: "Modular course schema 的 main benefit 是什么？", options: ["It makes every course hard-coded", "It lets the same interface load different course packs", "It removes the need for data validation", "It prevents deployment"], correctAnswers: ["It lets the same interface load different course packs"], explanation: "当 content stored as replaceable structured data，system becomes course-agnostic。" } },
  "q-prototype-scope": { zh: { question: "对当前粗略演示，哪种说法最稳妥？", options: ["它完整训练了新的 AI 导师", "它使用合成数据，并为未来导入功能做好 AI-ready 设计", "它包含真实课程材料", "它保证考试表现"], correctAnswers: ["它使用合成数据，并为未来导入功能做好 AI-ready 设计"], explanation: "演示应清楚说明当前实现，同时展示扩展路径。" }, mix: { question: "Current rough demo 最 safe 的 statement 是哪一个？", options: ["It fully trains a new AI tutor", "It uses synthetic data and is AI-ready for future ingestion", "It contains real course materials", "It guarantees exam performance"], correctAnswers: ["It uses synthetic data and is AI-ready for future ingestion"], explanation: "Demo should describe the current implementation clearly while showing extension path。" } }
};

const trapI18n = {
  "trap-passive-reading": { zh: { wrong: "复习系统只需要清楚展示笔记。", correct: "强复习系统应创造提取、反馈和按计划复习的行动。", why: "清楚笔记有帮助，但互动回忆能产生更有用的学习信号。" }, mix: { wrong: "Revision system 只需要 display notes clearly。", correct: "Strong revision system 应 create retrieval、feedback 和 scheduled review actions。", why: "Clear notes 有帮助，但 interactive recall 产生更有用的 learning signals。" } },
  "trap-overloaded-dashboard": { zh: { wrong: "面板越多，学习仪表盘就越聪明。", correct: "有用的仪表盘应降低认知负荷，并明确下一步复习行动。", why: "太多同时出现的信号会让系统更难使用。" }, mix: { wrong: "More panels always mean smarter learning dashboard。", correct: "Useful dashboard 应 reduce cognitive load，并 clarify next review action。", why: "Too many simultaneous signals 会让 system harder to use。" } },
  "trap-score-equals-mastery": { zh: { wrong: "最近一次测验分数就等于掌握程度。", correct: "掌握程度应由重复尝试、概念映射、时间间隔和错误等多种信号估计。", why: "单次回答可能是运气、已过期或受题目措辞影响。" }, mix: { wrong: "Latest quiz score 等于 mastery。", correct: "Mastery 应由 repeated attempts、concept mapping、time gaps 和 mistakes 等 signals 估计。", why: "Single answer 可能 lucky、stale 或 affected by wording。" } },
  "trap-confidence-is-accuracy": { zh: { wrong: "学习者感觉自信，就说明概念已掌握。", correct: "信心应与实际表现进行校准。", why: "高信心错误是尤其重要的诊断信号。" }, mix: { wrong: "If learner feels confident，concept is mastered。", correct: "Confidence should be calibrated against actual performance。", why: "High-confidence mistakes 是 especially important diagnostic signals。" } },
  "trap-train-llm-wording": { zh: { wrong: "下一步是在每门课上训练一个大语言模型。", correct: "更安全的下一步是基于用户提供材料进行 LLM/RAG 内容导入。", why: "训练或微调的说法可能显得不现实，并引发隐私/版权顾虑。" }, mix: { wrong: "Next step is to train a large language model on every course。", correct: "Safer next step 是使用 user-provided materials 做 LLM/RAG-based content ingestion。", why: "Training/fine-tuning claims 可能 unrealistic，并 raise privacy/copyright concerns。" } },
  "trap-ungrounded-generation": { zh: { wrong: "生成题只要听起来流畅就可以信任。", correct: "生成题应基于来源材料，并检查歧义。", why: "流畅输出仍可能错误、无依据或与课程不匹配。" }, mix: { wrong: "Generated quizzes 只要 sound fluent 就可以 trusted。", correct: "Generated quizzes should be grounded in source material and checked for ambiguity。", why: "Fluent output 仍可能 wrong、unsupported 或 misaligned with the course。" } },
  "trap-feature-list-without-data": { zh: { wrong: "原型功能名越多就越强。", correct: "当功能连接到清晰数据模型和用户流程时，原型更强。", why: "数据结构决定系统能否扩展到其他课程。" }, mix: { wrong: "Prototype 有 many feature names 就 strong。", correct: "Features connected to clear data model and user flow 时，prototype 更强。", why: "Data structure makes system extensible to other courses。" } },
  "trap-demo-overclaim": { zh: { wrong: "演示应声称自己是完整的自适应 AI 导师。", correct: "演示应说明它是粗略的、使用合成数据的、AI-ready 原型。", why: "清晰的产品边界让原型更容易评估和改进。" }, mix: { wrong: "Demo should claim to be a complete adaptive AI tutor。", correct: "Demo should state it is a rough、synthetic-data、AI-ready prototype。", why: "Clear product boundaries make prototype easier to evaluate and iterate。" } }
};

const answerI18n = {
  "ans-learning-science-design": { zh: { question: "解释学习科学原则如何塑造复习系统设计。", skeleton: ["从被动复习的问题出发。", "解释间隔重复如何对应计划复习。", "解释主动回忆如何对应先尝试的练习。", "解释模块化卡片如何降低认知负荷。", "把错误记录连接到元认知复习。"], fullAnswer: "该系统旨在把学生从被动阅读转向主动、按计划的复习。间隔重复支持到期复习队列，主动回忆支持测验和长答案提示，认知负荷降低支持模块化卡片和聚焦页面，元认知复习则支持错题追踪和薄弱区域反思。", commonMistakes: ["只说界面功能，而没有解释学习原则。", "把间隔重复只当成普通提醒。"] }, mix: { question: "Explain how learning-science principles shape the revision system design。", skeleton: ["Start from passive revision 的问题。", "Explain spaced repetition as scheduled review。", "Explain active recall as try-first practice。", "Explain cognitive load reduction through modular cards。", "Connect mistake records to metacognitive review。"], fullAnswer: "The system 旨在把 students 从 passive reading 转向 active, scheduled review。Spaced repetition motivates due review queue，active recall motivates quizzes and long-answer prompts，cognitive load reduction motivates modular cards and focused pages，metacognitive review motivates mistake tracking and weak-area reflection。", commonMistakes: ["只列 UI features，不解释 learning principles。", "把 spaced repetition 当成普通 reminders。"] } },
  "ans-cognitive-diagnosis": { zh: { question: "描述用户学习记录如何支持认知诊断。", skeleton: ["定义知识组件。", "把测验题和错误映射到概念。", "把重复尝试作为证据。", "把信心校准作为未来信号。", "用结果推荐复习优先级。"], fullAnswer: "当原始尝试记录连接到知识组件时，学习记录才真正有用。正确性、重复错误、复习评分和信心可以组合成暂定的掌握程度估计。这些估计不应被当作固定标签，而应作为排序薄弱区域、决定下一步复习内容的证据。", commonMistakes: ["把最新分数直接等同于掌握程度。", "没有把错误映射到具体概念。"] }, mix: { question: "Describe how user learning records can support cognitive diagnosis。", skeleton: ["Define knowledge components。", "Map quiz items and mistakes to concepts。", "Use repeated attempts as evidence。", "Add confidence calibration as future signal。", "Use result to recommend review priorities。"], fullAnswer: "Learning records 在 raw attempts connected to knowledge components 时才 useful。Correctness、repeated errors、review ratings 和 confidence 可以 combine into tentative mastery estimates。这些 estimates 不应视为 fixed labels，而应作为 ranking weak areas and choosing next review 的 evidence。", commonMistakes: ["把 latest score 直接当成 mastery。", "没有把 mistakes 映射到 specific concepts。"] } },
  "ans-ai-extension-roadmap": { zh: { question: "概述复习系统未来的 AI/RAG 扩展。", skeleton: ["从用户提供的材料开始。", "解析并切分材料为可检索单元。", "使用检索为生成结果提供 grounding。", "把概念、测验、误区和总结生成为结构化对象。", "加入课程包前应用护栏。"], fullAnswer: "未来 AI 扩展可允许用户上传课程笔记或幻灯片，抽取结构化片段，检索相关语境，并生成概念卡、测验等复习对象。最安全的设计是基于 RAG，而不是声称训练新模型。生成内容应包含来源约束、可编辑结构化输出和可选人工审核。", commonMistakes: ["声称已经训练完整 AI 导师。", "没有提来源约束和验证。"] }, mix: { question: "Outline a future AI/RAG extension for the revision hub。", skeleton: ["Start with user-provided materials。", "Parse and chunk materials into retrievable units。", "Use retrieval to ground generated outputs。", "Generate concepts、quizzes、traps 和 summaries as structured objects。", "Apply guardrails before adding items to course pack。"], fullAnswer: "Future AI extension 可让 users upload course notes or slides，extract structured chunks，retrieve relevant context，并 generate review objects such as concept cards and quizzes。Safest design 是 RAG-based，而不是 claiming to train a new model。Generated content 应包含 source grounding、editable structured output 和 optional human review。", commonMistakes: ["Claim 已经 trained a complete AI tutor。", "不提 source grounding 和 verification。"] } },
  "ans-prototype-evaluation": { zh: { question: "如何把该原型评估为功能性且具备研究扩展潜力的系统？", skeleton: ["描述当前 MVP 范围。", "解释模块化课程 schema。", "解释本地学习记录和复习队列。", "讨论部署如何作为可分享演示证据。", "描述未来如何用真实用户日志评估。"], fullAnswer: "粗略原型可通过能否加载课程包、展示模块化复习单元、本地记录测验/复习交互，并生成有意义的复习页面来评估。它具有研究扩展潜力，因为数据模型后续可支持学习分析、知识追踪和自适应推荐；当前版本仍然保持为合成数据演示。", commonMistakes: ["过度宣称生产就绪。", "忽视本地 MVP 存储与后端数据基础设施之间的差异。"] }, mix: { question: "How can the prototype be evaluated as a functional and research-ready system？", skeleton: ["Describe current MVP scope。", "Explain modular course schema。", "Explain local learning log and review queue。", "Discuss deployment as shareable demo evidence。", "Describe future evaluation with real user logs。"], fullAnswer: "Rough prototype 可通过是否 loads course packs、displays modular review units、records quiz/review interactions locally，并 produces meaningful review pages 来 evaluation。它 research-ready 的意义在于 data model 后续可支持 learning analytics、knowledge tracing 和 adaptive recommendation，同时 current version remains a synthetic-data demonstration。", commonMistakes: ["Overclaim production readiness。", "Ignoring difference between local MVP storage and backend infrastructure。"] } }
};

const formulaI18n = {
  "formula-forgetting-curve": { zh: { title: "简化遗忘曲线", variables: [{ symbol: "R(t)", meaning: "时间 t 后的估计保持率" }, { symbol: "S", meaning: "记忆强度或稳定性参数" }], example: "如果成功回忆后记忆强度 S 增加，下一次复习就可以安排得更晚。", examNote: "在该粗略演示中，它只是间隔复习的概念锚点，不是精确用户模型。" }, mix: { title: "Simplified Forgetting Curve", variables: [{ symbol: "R(t)", meaning: "estimated retention after time t" }, { symbol: "S", meaning: "memory strength or stability parameter" }], example: "如果 successful recall 后 memory strength S increases，next review 可以 scheduled later。", examNote: "Use it as conceptual anchor for spaced review，不作为 rough demo 中的 precise user model。" } },
  "formula-mastery-update": { zh: { title: "简化掌握度更新", variables: [{ symbol: "p", meaning: "当前掌握程度估计" }, { symbol: "r", meaning: "新的反应信号，例如 0 或 1" }, { symbol: "\\alpha", meaning: "更新率" }], example: "正确答案可使 p 上升，错误答案可使 p 下降。", examNote: "这是用于解释自适应复习逻辑的简化占位公式。" }, mix: { title: "Toy Mastery Update", variables: [{ symbol: "p", meaning: "current mastery estimate" }, { symbol: "r", meaning: "new response signal, such as 0 or 1" }, { symbol: "\\alpha", meaning: "update rate" }], example: "Correct answer can move p upward，wrong answer can move it downward。", examNote: "Simplified placeholder for explaining adaptive review logic。" } },
  "formula-cosine-similarity": { zh: { title: "检索相似度", variables: [{ symbol: "a,b", meaning: "查询和文档片段的嵌入向量" }, { symbol: "\\cos(\\theta)", meaning: "相似度分数" }], example: "RAG 系统可检索与问题嵌入向量接近的文档片段。", examNote: "可作为解释基于检索的课程内容导入的简洁技术说明。" }, mix: { title: "Retrieval Similarity", variables: [{ symbol: "a,b", meaning: "embedding vectors for query and document chunk" }, { symbol: "\\cos(\\theta)", meaning: "similarity score" }], example: "RAG system 可能 retrieve chunks whose embeddings are close to question embedding。", examNote: "Useful as simple technical explanation for retrieval-based course-content ingestion。" } },
  "formula-priority-score": { zh: { title: "原型复习优先级分数", variables: [{ symbol: "M", meaning: "错误频率" }, { symbol: "D", meaning: "到期复习信号" }, { symbol: "E", meaning: "考试或教师优先级" }, { symbol: "C", meaning: "信心不匹配信号" }], example: "反复出错且即将到期的项目应在仪表盘上更靠前。", examNote: "这是使用学习型推荐模型前的透明设计占位公式。" }, mix: { title: "Prototype Review Priority Score", variables: [{ symbol: "M", meaning: "mistake frequency" }, { symbol: "D", meaning: "due-review signal" }, { symbol: "E", meaning: "exam or instructor priority" }, { symbol: "C", meaning: "confidence mismatch signal" }], example: "Repeated mistakes 且 upcoming due date 的 item 应 appear higher on dashboard。", examNote: "Transparent design placeholder before learned recommendation models。" } }
};

const figureI18n = {
  "fig-review-cycle": { zh: { title: "学习科学复习循环", alt: "从编码到回忆、诊断和计划复习的四步循环。", keyVisualCue: "注意循环：复习不是线性阅读，而是带反馈的重复回忆。", recognitionQuestion: "图中哪一部分对应主动回忆？" }, mix: { title: "Learning-Science Review Cycle", alt: "从 encoding 到 recall、diagnosis 和 scheduled review 的 four-step cycle。", keyVisualCue: "Look for the loop：review 不是 linear reading，而是 repeated recall with feedback。", recognitionQuestion: "Which part of the diagram corresponds to active recall？" } },
  "fig-diagnosis-loop": { zh: { title: "认知诊断循环", alt: "从测验事件到知识地图、薄弱区域和复习路径的循环。", keyVisualCue: "测验事件只有在映射到知识组件后才有用。", recognitionQuestion: "什么把原始测验尝试转化为诊断证据？" }, mix: { title: "Cognitive Diagnosis Loop", alt: "从 quiz events 到 knowledge map、weak areas 和 review path 的 loop。", keyVisualCue: "Quiz events are useful only after mapped to knowledge components。", recognitionQuestion: "What turns raw quiz attempts into diagnostic evidence？" } },
  "fig-rag-pipeline": { zh: { title: "AI-ready 内容导入流程", alt: "从上传到切分、检索、生成和验证的流程。", keyVisualCue: "关键转变是从原始材料到有来源约束的生成复习对象。", recognitionQuestion: "为什么验证放在生成之后？" }, mix: { title: "AI-Ready Content Ingestion Pipeline", alt: "从 upload 到 chunking、retrieval、generation 和 verification 的 pipeline。", keyVisualCue: "Key transition 是从 raw materials 到 grounded generated review objects。", recognitionQuestion: "Why is verification placed after generation？" } },
  "fig-modular-architecture": { zh: { title: "模块化复习系统架构", alt: "包含课程 JSON、前端 UI 和本地学习记录的模块化系统架构。", keyVisualCue: "课程内容与 UI 分离，因此不同课程可以被加载。", recognitionQuestion: "哪个模块让系统与具体课程解耦？" }, mix: { title: "Modular Revision Hub Architecture", alt: "包含 course JSON、frontend UI 和 local learning log 的 modular system architecture。", keyVisualCue: "Course content separated from UI，所以 different courses can be loaded。", recognitionQuestion: "Which block makes the system course-agnostic？" } }
};

export function applyDemoCourseI18n(course) {
  return {
    ...course,
    lectures: addI18n(course.lectures, lectureI18n),
    concepts: addI18n(course.concepts, conceptI18n),
    quizzes: addI18n(course.quizzes, quizI18n),
    traps: addI18n(course.traps, trapI18n),
    answers: addI18n(course.answers, answerI18n),
    formulas: addI18n(course.formulas, formulaI18n),
    figures: addI18n(course.figures, figureI18n),
    trackPatches: addNestedI18n(course.trackPatches, {}, "trackId")
  };
}
